import type { Race } from "../models/races/Race"

export const RACE_NAMES: Record<Race, string> = {
  aarakocra: "Aarakocra",
  aasimar: "Aasimar",
  bugbear: "Bugbear",
  centaur: "Centauro",
  changeling: "Changeling",
  dragonborn: "Draconato",
  dwarf: "Anão",
  duergar: "Duergar",
  elf: "Elfo",
  eladrin: "Eladrin",
  fairy: "Fada",
  firbolg: "Firbolg",
  genasi: "Genasi",
  giff: "Giff",
  githyanki: "Githyanki",
  githzerai: "Githzerai",
  gnome: "Gnomo",
  "deep-gnome": "Gnomo das Profundezas",
  goblin: "Goblin",
  goliath: "Golias",
  "half-elf": "Meio-elfo",
  "half-giant": "Meio-gigante",
  "half-orc": "Meio-orc",
  halfling: "Halfling",
  harengon: "Harengon",
  hobgoblin: "Hobgoblin",
  human: "Humano",
  kenku: "Kenku",
  kobold: "Kobold",
  leonin: "Leonin",
  lizardfolk: "Povo-lagarto",
  loxodon: "Loxodon",
  minotaur: "Minotauro",
  orc: "Orc",
  owlin: "Owlin",
  satyr: "Sátiro",
  "shadar-kai": "Shadar-kai",
  shifter: "Shifter",
  tabaxi: "Tabaxi",
  "thri-kreen": "Thri-kreen",
  tiefling: "Tiefling",
  tortle: "Tortle",
  triton: "Tritão",
  vedalken: "Vedalken",
  verdan: "Verdan",
  warforged: "Forjado Bélico",
  "yuan-ti": "Yuan-ti",
}

export function formatRaceName(race: Race): string {
  return RACE_NAMES[race]
}
