from pathlib import Path


def read(path: str) -> str:
    return Path(path).read_text()


def write(path: str, text: str) -> None:
    Path(path).write_text(text)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"anchor not found: {label}")
    return text.replace(old, new, 1)


# The first phase script intentionally reaches the server actor after all model/
# protocol patches. Its only known stale anchor is inside this actor. Reapply the
# actor edits from the original source, then continue with the UI files.
path = "session-server/src/routes/initiative/InitiativeSessionActor.ts"
text = read(path)
text = replace_once(
    text,
    """    if (connection.role !== \"MASTER\") {\n      sendError(webSocket, \"MASTER_REQUIRED\", \"Only the MASTER can mutate initiative state.\");\n      return;\n    }\n\n    if (parsed.type === \"session.initiative.initialize\") {\n""",
    """    if (\n      connection.role !== \"MASTER\" &&\n      !(parsed.type === \"session.initiative.operation\" && parsed.operation.type === \"initiative.deathSaves.set\")\n    ) {\n      sendError(webSocket, \"MASTER_REQUIRED\", \"Only the MASTER can mutate initiative state.\");\n      return;\n    }\n\n    if (parsed.type === \"session.initiative.initialize\") {\n""",
    "allow player death saves operation",
)
text = replace_once(
    text,
    """    const current = normalizeInitiativeSession(state.session as Partial<InitiativeSession>);\n    const before = structuredClone(state);\n    const result = applyInitiativeOperation(current, operation);\n""",
    """    const current = normalizeInitiativeSession(state.session as Partial<InitiativeSession>);\n    if (connection.role !== \"MASTER\" && operation.type === \"initiative.deathSaves.set\") {\n      const entry = current.entries.find((candidate) => candidate.id === operation.entryId);\n      const linkedCharacterId = linkedCharacterIdForEntry(entry);\n      const linkedHp = linkedCharacterId ? hp[linkedCharacterId] : undefined;\n      if (\n        !entry ||\n        entry.sourceType !== \"character\" ||\n        !linkedCharacterId ||\n        linkedHp?.ownerUserId !== connection.userId ||\n        !current.deathSaveOwnerCanEdit\n      ) {\n        sendError(webSocket, \"DEATH_SAVES_ACCESS_DENIED\", \"This player cannot edit these death saves.\");\n        return;\n      }\n    }\n    const before = structuredClone(state);\n    const result = applyInitiativeOperation(current, operation);\n""",
    "validate player death saves",
)
text = replace_once(
    text,
    """    const previousAbilities: Record<string, SessionAbilityState> = {};\n    const changedAbilityIds = new Set<string>();\n    if (runtimeConfig) {\n""",
    """    const previousAbilities: Record<string, SessionAbilityState> = {};\n    const changedAbilityIds = new Set<string>();\n\n    const deathSaveEntry = operation.type === \"initiative.deathSaves.set\"\n      ? result.session.entries.find((entry) => entry.id === operation.entryId)\n      : operation.type === \"initiative.entry.update\" && \"deathSaves\" in operation.patch\n        ? result.session.entries.find((entry) => entry.id === operation.entryId)\n        : undefined;\n    const deathSaveCharacterId = linkedCharacterIdForEntry(deathSaveEntry);\n    if (deathSaveEntry?.deathSaves && deathSaveCharacterId) {\n      const storedAbility = abilities[deathSaveCharacterId];\n      if (storedAbility?.initialized) {\n        previousAbilities[deathSaveCharacterId] = structuredClone(storedAbility);\n        const character = CharacterTemplate.fromJSON(storedAbility.character as Partial<CharacterTemplateProps>);\n        const updatedCharacter = character.with(\"deathSaves\", { ...deathSaveEntry.deathSaves });\n        abilities[deathSaveCharacterId] = {\n          characterId: deathSaveCharacterId,\n          character: updatedCharacter.toJSON() as unknown as Record<string, unknown>,\n          initialized: true,\n          revision: storedAbility.revision + 1,\n        };\n        changedAbilityIds.add(deathSaveCharacterId);\n      }\n    }\n\n    if (runtimeConfig) {\n""",
    "sync death saves to ability snapshot",
)
text = replace_once(
    text,
    """    case \"initiative.viewMode.set\": {\n      if (current.viewMode === operation.viewMode) return invalid(\"INITIATIVE_VIEW_UNCHANGED\", \"Initiative already uses this view mode.\");\n      return { ok: true, session: { ...current, viewMode: operation.viewMode, updatedAt: Date.now() }, operation };\n    }\n    case \"initiative.reset\": {\n""",
    """    case \"initiative.viewMode.set\": {\n      if (current.viewMode === operation.viewMode) return invalid(\"INITIATIVE_VIEW_UNCHANGED\", \"Initiative already uses this view mode.\");\n      return { ok: true, session: { ...current, viewMode: operation.viewMode, updatedAt: Date.now() }, operation };\n    }\n    case \"initiative.settings.update\": {\n      const visibility = operation.patch.deathSaveVisibility;\n      if (visibility !== undefined && visibility !== \"masterOnly\" && visibility !== \"owner\" && visibility !== \"everyone\") {\n        return invalid(\"INITIATIVE_SETTINGS_INVALID\", \"Invalid death-save visibility setting.\");\n      }\n      if (operation.patch.deathSaveOwnerCanEdit !== undefined && typeof operation.patch.deathSaveOwnerCanEdit !== \"boolean\") {\n        return invalid(\"INITIATIVE_SETTINGS_INVALID\", \"Invalid death-save edit setting.\");\n      }\n      return {\n        ok: true,\n        session: {\n          ...current,\n          ...(visibility !== undefined ? { deathSaveVisibility: visibility } : {}),\n          ...(operation.patch.deathSaveOwnerCanEdit !== undefined ? { deathSaveOwnerCanEdit: operation.patch.deathSaveOwnerCanEdit } : {}),\n          updatedAt: Date.now(),\n        },\n        operation,\n      };\n    }\n    case \"initiative.deathSaves.set\": {\n      const existing = current.entries.find((entry) => entry.id === operation.entryId);\n      if (!existing || existing.sourceType !== \"character\") return invalid(\"INITIATIVE_ENTRY_NOT_FOUND\", \"Player initiative entry was not found.\");\n      if (!existing.downed && (existing.currentHp ?? 0) > 0) return invalid(\"DEATH_SAVES_NOT_ACTIVE\", \"Death saves are only active while the character is downed.\");\n      const deathSaves = { successes: operation.successes, failures: operation.failures };\n      return {\n        ok: true,\n        session: updateInitiativeEntry(current, operation.entryId, (entry) => ({ ...entry, deathSaves })),\n        operation,\n      };\n    }\n    case \"initiative.reset\": {\n""",
    "initiative actor settings/death saves cases",
)
text = replace_once(
    text,
    """    sourceType,\n    name,\n    imageUrl: typeof value.imageUrl === \"string\" && value.imageUrl.trim() ? value.imageUrl.trim() : undefined,\n""",
    """    sourceType,\n    name,\n    realName: typeof value.realName === \"string\" && value.realName.trim() ? value.realName.trim() : undefined,\n    basicName: typeof value.basicName === \"string\" && value.basicName.trim() ? value.basicName.trim() : undefined,\n    customName: typeof value.customName === \"string\" && value.customName.trim() ? value.customName.trim() : undefined,\n    revealRealName: value.revealRealName === true,\n    imageUrl: typeof value.imageUrl === \"string\" && value.imageUrl.trim() ? value.imageUrl.trim() : undefined,\n""",
    "server normalize entry names",
)
text = replace_once(
    text,
    """    defeated: value.defeated === true,\n    conditions: Array.isArray(value.conditions) ? structuredClone(value.conditions) as InitiativeEntry[\"conditions\"] : [],\n""",
    """    defeated: value.defeated === true,\n    downed: value.downed === true,\n    defeatReason: value.defeatReason === \"manual\" || value.defeatReason === \"zeroHp\" ? value.defeatReason : undefined,\n    deathSaves: sourceType === \"character\" ? normalizeDeathSaves(value.deathSaves) : undefined,\n    conditions: Array.isArray(value.conditions) ? structuredClone(value.conditions) as InitiativeEntry[\"conditions\"] : [],\n""",
    "server normalize entry combat fields",
)
text = replace_once(
    text,
    """  if (typeof value.name === \"string\" && value.name.trim()) patch.name = value.name.trim();\n  for (const key of [\"initiative\", \"initiativeBonus\", \"dexterity\", \"armorClass\", \"currentHp\", \"maxHp\", \"temporaryHp\"] as const) {\n""",
    """  if (typeof value.name === \"string\" && value.name.trim()) patch.name = value.name.trim();\n  for (const key of [\"realName\", \"basicName\", \"customName\"] as const) {\n    if (!(key in value)) continue;\n    patch[key] = typeof value[key] === \"string\" && value[key].trim() ? value[key].trim() : undefined;\n  }\n  if (typeof value.revealRealName === \"boolean\") patch.revealRealName = value.revealRealName;\n  for (const key of [\"initiative\", \"initiativeBonus\", \"dexterity\", \"armorClass\", \"currentHp\", \"maxHp\", \"temporaryHp\"] as const) {\n""",
    "server normalize patch names",
)
text = replace_once(
    text,
    """  if (typeof value.hidden === \"boolean\") patch.hidden = value.hidden;\n  if (typeof value.defeated === \"boolean\") patch.defeated = value.defeated;\n  if (Array.isArray(value.conditions)) patch.conditions = structuredClone(value.conditions) as InitiativeEntry[\"conditions\"];\n""",
    """  if (typeof value.hidden === \"boolean\") patch.hidden = value.hidden;\n  if (typeof value.defeated === \"boolean\") patch.defeated = value.defeated;\n  if (typeof value.downed === \"boolean\") patch.downed = value.downed;\n  if (value.defeatReason === \"manual\" || value.defeatReason === \"zeroHp\" || value.defeatReason === undefined) patch.defeatReason = value.defeatReason as InitiativeEntry[\"defeatReason\"];\n  if (\"deathSaves\" in value) patch.deathSaves = normalizeDeathSaves(value.deathSaves);\n  if (Array.isArray(value.conditions)) patch.conditions = structuredClone(value.conditions) as InitiativeEntry[\"conditions\"];\n""",
    "server normalize patch combat fields",
)
helper_anchor = """function optionalFinite(value: unknown): number | undefined {\n"""
actor_helpers = """function linkedCharacterIdForEntry(entry: InitiativeEntry | undefined): string | undefined {\n  if (!entry?.sourceId?.trim()) return undefined;\n  if (entry.sourceId.startsWith(\"compendium:\")) return undefined;\n  return entry.sourceId.trim();\n}\n\nfunction normalizeDeathSaves(value: unknown): InitiativeEntry[\"deathSaves\"] {\n  const record = value && typeof value === \"object\" && !Array.isArray(value)\n    ? value as Record<string, unknown>\n    : {};\n  const successes = typeof record.successes === \"number\" && Number.isFinite(record.successes)\n    ? Math.max(0, Math.min(3, Math.trunc(record.successes)))\n    : 0;\n  const failures = typeof record.failures === \"number\" && Number.isFinite(record.failures)\n    ? Math.max(0, Math.min(3, Math.trunc(record.failures)))\n    : 0;\n  return { successes, failures };\n}\n\n"""
text = replace_once(text, helper_anchor, actor_helpers + helper_anchor, "initiative actor helpers")
write(path, text)

# Roster types
path = "src/features/initiative/initiativeRosterTypes.ts"
text = read(path)
text = replace_once(text, "  onOpen: (entryId: string) => void\n  onCondition: (entryId: string) => void\n", "  onOpen: (entryId: string) => void\n  onRename?: (entryId: string) => void\n  onCondition: (entryId: string) => void\n", "roster rename prop")
write(path, text)

# Entry parts
path = "src/features/initiative/InitiativeEntryParts.tsx"
text = read(path)
text = replace_once(text, """import type {\n  InitiativeConditionDuration,\n  InitiativeEntry,\n  InitiativeSide,\n} from \"../../models/initiative/Initiative\"\n""", """import {\n  initiativeEntryDisplayName,\n  type InitiativeConditionDuration,\n  type InitiativeEntry,\n  type InitiativeSide,\n} from \"../../models/initiative/Initiative\"\n""", "entry parts display helper import")
text = replace_once(text, """  showTemporaryHp = true,\n}: {\n  entry: InitiativeEntry\n  onOpen?: () => void\n  showTemporaryHp?: boolean\n}) {\n""", """  showTemporaryHp = true,\n  viewer = \"master\",\n}: {\n  entry: InitiativeEntry\n  onOpen?: () => void\n  showTemporaryHp?: boolean\n  viewer?: \"master\" | \"player\"\n}) {\n""", "entry identity viewer prop")
text = replace_once(text, "          {entry.name}\n", "          {initiativeEntryDisplayName(entry, viewer)}\n", "entry identity display name")
anchor = "export function TradeControls({\n"
death_counter = """export function DeathSaveCounter({\n  entry,\n  editable = false,\n  onChange,\n}: {\n  entry: InitiativeEntry\n  editable?: boolean\n  onChange?: (deathSaves: { successes: number; failures: number }) => void\n}) {\n  if (entry.sourceType !== \"character\" || !entry.downed) return null\n  const saves = entry.deathSaves ?? { successes: 0, failures: 0 }\n  const set = (kind: \"successes\" | \"failures\", delta: number) => {\n    if (!editable || !onChange) return\n    onChange({\n      ...saves,\n      [kind]: Math.max(0, Math.min(3, saves[kind] + delta)),\n    })\n  }\n  return (\n    <div className=\"grid gap-1 text-[10px] text-textMuted\">\n      <div className=\"font-semibold uppercase tracking-wide text-textH\">Caído · Saves de morte</div>\n      {([\"successes\", \"failures\"] as const).map((kind) => (\n        <div key={kind} className=\"flex items-center gap-1.5\">\n          <span className={kind === \"successes\" ? \"text-emerald-300\" : \"text-danger\"}>\n            {kind === \"successes\" ? \"Sucessos\" : \"Falhas\"}\n          </span>\n          <div className=\"flex gap-1\">\n            {[0, 1, 2].map((index) => (\n              <span key={index} className={[\n                \"h-2.5 w-2.5 rounded-full border\",\n                index < saves[kind]\n                  ? kind === \"successes\" ? \"border-emerald-300 bg-emerald-300\" : \"border-danger bg-danger\"\n                  : \"border-border bg-bg\",\n              ].join(\" \")} />\n            ))}\n          </div>\n          {editable ? (\n            <div className=\"ml-1 flex gap-1\">\n              <button type=\"button\" className=\"rounded border border-border px-1\" onClick={() => set(kind, -1)}>−</button>\n              <button type=\"button\" className=\"rounded border border-border px-1\" onClick={() => set(kind, 1)}>+</button>\n            </div>\n          ) : null}\n        </div>\n      ))}\n    </div>\n  )\n}\n\n"""
text = replace_once(text, anchor, death_counter + anchor, "death save counter component")
write(path, text)

# Table
path = "src/features/initiative/InitiativeTable.tsx"
text = read(path)
text = replace_once(text, 'import { Play, Skull, Trash2 } from "lucide-react"', 'import { Pencil, Play, Skull, Trash2 } from "lucide-react"', "table pencil icon")
text = replace_once(text, "  ArmorClassEditor,\n  ConditionChips,\n  EntryIdentity,\n", "  ArmorClassEditor,\n  ConditionChips,\n  DeathSaveCounter,\n  EntryIdentity,\n", "table death counter import")
text = replace_once(text, "  onOpen,\n  onCondition,\n", "  onOpen,\n  onRename,\n  onCondition,\n", "table rename destructure")
text = replace_once(text, """        <td className=\"px-3 py-3\">\n          <HitPointEditor entry={entry} patchEntry={patchEntry} />\n        </td>\n""", """        <td className=\"px-3 py-3\">\n          <div className=\"grid gap-2\">\n            <HitPointEditor entry={entry} patchEntry={patchEntry} />\n            <DeathSaveCounter entry={entry} editable onChange={(deathSaves) => patchEntry(entry.id, { deathSaves })} />\n          </div>\n        </td>\n""", "table death saves render")
text = replace_once(text, "          <div className=\"flex justify-end gap-1\">\n            <Button\n", """          <div className=\"flex justify-end gap-1\">\n            {onRename ? (\n              <Button size=\"icon\" variant=\"ghost\" title=\"Nome no combate\" onClick={() => onRename(entry.id)}>\n                <Pencil className=\"h-4 w-4\" />\n              </Button>\n            ) : null}\n            <Button\n""", "table rename button")
text = replace_once(text, "                patchEntry(entry.id, { defeated: !entry.defeated })\n", """                patchEntry(entry.id, {\n                  defeated: !entry.defeated,\n                  downed: entry.defeated ? entry.downed : false,\n                  defeatReason: entry.defeated ? undefined : \"manual\",\n                })\n""", "table manual defeat reason")
write(path, text)

# Cards
path = "src/features/initiative/InitiativeCards.tsx"
text = read(path)
text = replace_once(text, 'import { Skull, Trash2 } from "lucide-react"', 'import { Pencil, Skull, Trash2 } from "lucide-react"', "cards pencil icon")
text = replace_once(text, "  ConditionChips,\n  EntryIdentity,\n  TradeControls,\n", "  ConditionChips,\n  DeathSaveCounter,\n  EntryIdentity,\n  TradeControls,\n", "cards death counter import")
text = replace_once(text, "                    showTemporaryHp={showPrivateStats}\n                  />\n", "                    showTemporaryHp={showPrivateStats}\n                    viewer={readOnly ? \"player\" : \"master\"}\n                  />\n", "cards viewer")
text = replace_once(text, "                <div className=\"mt-4 flex-1\">\n", """                {entry.downed && showPrivateStats ? (\n                  <div className=\"mt-3 rounded-lg border border-danger/40 bg-danger/10 p-2\">\n                    <DeathSaveCounter entry={entry} />\n                  </div>\n                ) : null}\n\n                <div className=\"mt-4 flex-1\">\n""", "cards death saves render")
text = replace_once(text, "                    <div className=\"flex gap-1\">\n                      <Button\n", """                    <div className=\"flex gap-1\">\n                      {props.onRename ? (\n                        <Button size=\"icon\" variant=\"ghost\" title=\"Nome no combate\" onClick={() => props.onRename?.(entry.id)}>\n                          <Pencil className=\"h-4 w-4\" />\n                        </Button>\n                      ) : null}\n                      <Button\n""", "cards rename button")
text = replace_once(text, """                          props.patchEntry(entry.id, {\n                            defeated: !entry.defeated,\n                          })\n""", """                          props.patchEntry(entry.id, {\n                            defeated: !entry.defeated,\n                            downed: entry.defeated ? entry.downed : false,\n                            defeatReason: entry.defeated ? undefined : \"manual\",\n                          })\n""", "cards manual defeat reason")
write(path, text)

# Master view
path = "src/views/InitiativeView.tsx"
text = read(path)
text = replace_once(text, "  addInitiativeEntries,\n  advanceInitiativeTurn,\n", "  addInitiativeEntries,\n  advanceInitiativeTurn,\n  initiativeEntryDisplayName,\n", "initiative display import")
text = replace_once(text, "  const [conditionTargetId, setConditionTargetId] = useState<string>()\n  const [quickSheetEntryId, setQuickSheetEntryId] = useState<string>()\n", "  const [conditionTargetId, setConditionTargetId] = useState<string>()\n  const [renameTargetId, setRenameTargetId] = useState<string>()\n  const [renameValue, setRenameValue] = useState(\"\")\n  const [quickSheetEntryId, setQuickSheetEntryId] = useState<string>()\n", "initiative rename state")
text = replace_once(text, """  const conditionTarget = session.entries.find(\n    (entry) => entry.id === conditionTargetId,\n  )\n""", """  const conditionTarget = session.entries.find(\n    (entry) => entry.id === conditionTargetId,\n  )\n  const renameTarget = session.entries.find((entry) => entry.id === renameTargetId)\n""", "initiative rename target")
text = replace_once(text, "  function addSelectedCharacter() {\n", """  function openRename(entryId: string) {\n    const entry = session.entries.find((candidate) => candidate.id === entryId)\n    if (!entry) return\n    setRenameTargetId(entryId)\n    setRenameValue(entry.customName ?? \"\")\n  }\n\n  function addSelectedCharacter() {\n""", "initiative rename helper")
text = replace_once(text, """      name: selectedCreature.unique\n        ? selectedCreature.name\n        : `${selectedCreature.name} ${existingCopies + index + 1}`,\n      imageUrl: selectedCreature.sheetImageUrl,\n""", """      name: selectedCreature.unique\n        ? selectedCreature.name\n        : `${selectedCreature.name} ${existingCopies + index + 1}`,\n      realName: selectedCreature.unique\n        ? selectedCreature.name\n        : `${selectedCreature.name} ${existingCopies + index + 1}`,\n      basicName: selectedCreature.unique\n        ? selectedCreature.basicName\n        : `${selectedCreature.basicName} ${existingCopies + index + 1}`,\n      revealRealName: false,\n      imageUrl: selectedCreature.sheetImageUrl,\n""", "initiative creature names")
text = replace_once(text, "                    {creature.name}\n                    {disabled ? \" — já adicionada\" : \"\"}\n", "                    {creature.name}{creature.basicName !== creature.name ? ` — ${creature.basicName}` : \"\"}\n                    {disabled ? \" — já adicionada\" : \"\"}\n", "initiative creature dropdown")
text = replace_once(text, "    onOpen: setQuickSheetEntryId,\n    onCondition: setConditionTargetId,\n", "    onOpen: setQuickSheetEntryId,\n    onRename: openRename,\n    onCondition: setConditionTargetId,\n", "initiative roster rename")
text = replace_once(text, "        activeName={activeEntry?.name}\n", "        activeName={activeEntry ? initiativeEntryDisplayName(activeEntry, \"master\") : undefined}\n", "initiative active master name")
roster_anchor = """      <section className=\"rounded-xl border border-border bg-bg shadow-theme-sm\">\n        <div className=\"flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center sm:justify-between\">\n"""
settings = """      <section className=\"grid gap-3 rounded-xl border border-border bg-bg p-4 shadow-theme-sm md:grid-cols-[minmax(0,1fr)_auto]\">\n        <div>\n          <div className=\"text-sm font-semibold text-textH\">Saves de morte na iniciativa</div>\n          <p className=\"mt-1 text-xs text-textMuted\">Personagens em 0 PV ficam como Caídos; criaturas não-jogadoras são marcadas como derrotadas automaticamente.</p>\n        </div>\n        <div className=\"flex flex-wrap items-center gap-2\">\n          <select className={selectClassName} value={session.deathSaveVisibility} onChange={(event) => updateSession((current) => ({ ...current, deathSaveVisibility: event.target.value as typeof current.deathSaveVisibility, updatedAt: Date.now() }))}>\n            <option value=\"masterOnly\">Oculto dos jogadores</option>\n            <option value=\"owner\">Visível apenas ao dono</option>\n            <option value=\"everyone\">Visível para todos</option>\n          </select>\n          <label className=\"flex h-10 items-center gap-2 rounded-lg border border-border bg-bg px-3 text-xs text-textH\">\n            <input type=\"checkbox\" checked={session.deathSaveOwnerCanEdit} onChange={(event) => updateSession((current) => ({ ...current, deathSaveOwnerCanEdit: event.target.checked, updatedAt: Date.now() }))} />\n            Dono pode editar\n          </label>\n        </div>\n      </section>\n\n"""
text = replace_once(text, roster_anchor, settings + roster_anchor, "death save settings ui")
modal_anchor = "      {customOpen ? (\n"
rename_modal = """      {renameTarget ? (\n        <Modal title=\"Nome no combate\" onClose={() => setRenameTargetId(undefined)} className=\"max-w-md\">\n          <div className=\"grid gap-3\">\n            <div className=\"text-xs text-textMuted\">\n              Mestre: <strong className=\"text-textH\">{renameTarget.realName ?? renameTarget.name}</strong>\n              {renameTarget.basicName ? <> · jogadores: <strong className=\"text-textH\">{renameTarget.basicName}</strong></> : null}\n            </div>\n            <label className=\"grid gap-1 text-xs text-textMuted\">\n              Nome personalizado durante este combate\n              <Input value={renameValue} placeholder=\"Ex.: Snik, o goblin\" onChange={(event) => setRenameValue(event.target.value)} />\n            </label>\n            {renameTarget.realName && renameTarget.basicName && renameTarget.realName !== renameTarget.basicName ? (\n              <label className=\"flex items-center gap-2 rounded-lg border border-border bg-bg-subtle p-3 text-xs text-textH\">\n                <input type=\"checkbox\" checked={Boolean(renameTarget.revealRealName)} onChange={(event) => patchEntry(renameTarget.id, { revealRealName: event.target.checked })} />\n                Revelar nome verdadeiro aos jogadores\n              </label>\n            ) : null}\n            <div className=\"flex justify-end gap-2 border-t border-border pt-3\">\n              <Button variant=\"ghost\" onClick={() => { patchEntry(renameTarget.id, { customName: undefined }); setRenameValue(\"\"); }}>Limpar apelido</Button>\n              <Button variant=\"primary\" onClick={() => { patchEntry(renameTarget.id, { customName: renameValue.trim() || undefined }); setRenameTargetId(undefined); }}>Salvar</Button>\n            </div>\n          </div>\n        </Modal>\n      ) : null}\n\n"""
text = replace_once(text, modal_anchor, rename_modal + modal_anchor, "rename modal")
write(path, text)

# Player view
path = "src/views/InitiativePlayerView.tsx"
text = read(path)
text = replace_once(text, """import { InitiativeCards } from \"../features/initiative/InitiativeCards\"\nimport { useInitiativeSession } from \"../hooks/useInitiativeSession\"\nimport type { InitiativeEntry } from \"../models/initiative/Initiative\"\n""", """import { InitiativeCards } from \"../features/initiative/InitiativeCards\"\nimport { DeathSaveCounter } from \"../features/initiative/InitiativeEntryParts\"\nimport { useOptionalSessionRuntime } from \"../features/session-runtime/useSessionRuntime\"\nimport { useInitiativeSession } from \"../hooks/useInitiativeSession\"\nimport { initiativeEntryDisplayName, type InitiativeEntry } from \"../models/initiative/Initiative\"\n""", "player imports")
text = replace_once(text, "  const { session, hydrated } = useInitiativeSession()\n  const { visibleCharacters } = useCharacterContext()\n", "  const { session, hydrated } = useInitiativeSession()\n  const runtime = useOptionalSessionRuntime()\n  const { visibleCharacters } = useCharacterContext()\n", "player runtime")
text = replace_once(text, """  const canViewPrivateStats = (entry: InitiativeEntry) =>\n    Boolean(entry.sourceId && ownedCharacterIds.has(entry.sourceId))\n\n  const noop = () => undefined\n""", """  const canViewPrivateStats = (entry: InitiativeEntry) =>\n    Boolean(entry.sourceId && ownedCharacterIds.has(entry.sourceId))\n  const canViewDeathSaves = (entry: InitiativeEntry) =>\n    session.deathSaveVisibility === \"everyone\" ||\n    (session.deathSaveVisibility === \"owner\" && canViewPrivateStats(entry))\n  const canEditDeathSaves = (entry: InitiativeEntry) => Boolean(\n    runtime && runtime.status === \"connected\" && session.deathSaveOwnerCanEdit && canViewPrivateStats(entry),\n  )\n  const setDeathSaves = (entry: InitiativeEntry, deathSaves: { successes: number; failures: number }) => {\n    if (!canEditDeathSaves(entry)) return\n    runtime?.dispatchInitiativeOperation({ type: \"initiative.deathSaves.set\", characterId: \"session\", entryId: entry.id, successes: deathSaves.successes, failures: deathSaves.failures })\n  }\n\n  const noop = () => undefined\n""", "player death save helpers")
text = replace_once(text, "`Turno: ${active.name}`", "`Turno: ${initiativeEntryDisplayName(active, \"player\")}`", "player active public name")
text = replace_once(text, "              showPrivateStats={canViewPrivateStats(entry)}\n            />\n", "              showPrivateStats={canViewPrivateStats(entry)}\n              showDeathSaves={canViewDeathSaves(entry)}\n              editDeathSaves={canEditDeathSaves(entry)}\n              onDeathSaves={(deathSaves) => setDeathSaves(entry, deathSaves)}\n            />\n", "player readonly props")
text = replace_once(text, """  showPrivateStats,\n}: {\n  entry: InitiativeEntry\n  active: boolean\n  showPrivateStats: boolean\n}) {\n""", """  showPrivateStats,\n  showDeathSaves,\n  editDeathSaves,\n  onDeathSaves,\n}: {\n  entry: InitiativeEntry\n  active: boolean\n  showPrivateStats: boolean\n  showDeathSaves: boolean\n  editDeathSaves: boolean\n  onDeathSaves: (deathSaves: { successes: number; failures: number }) => void\n}) {\n""", "readonly death save props")
text = replace_once(text, "            {entry.name}\n", "            {initiativeEntryDisplayName(entry, \"player\")}\n", "player public entry name")
text = replace_once(text, """          {entry.defeated ? (\n            <span className=\"rounded-full border border-border px-2 py-1 text-[10px] text-textMuted\">\n              Derrotado\n            </span>\n          ) : null}\n""", """          {entry.downed ? (\n            <span className=\"rounded-full border border-danger/50 bg-danger/10 px-2 py-1 text-[10px] font-semibold text-danger\">Caído</span>\n          ) : entry.defeated ? (\n            <span className=\"rounded-full border border-border px-2 py-1 text-[10px] text-textMuted\">Derrotado</span>\n          ) : null}\n""", "player downed badge")
condition_block = """        {entry.conditions.length ? (\n          <div className=\"mt-2 flex flex-wrap gap-1.5\">\n            {entry.conditions.map((condition) => (\n              <span\n                key={condition.id}\n                title={condition.description}\n                className=\"rounded-full border border-border bg-bg-subtle px-2 py-1 text-[10px] text-textH\"\n              >\n                {condition.name}\n              </span>\n            ))}\n          </div>\n        ) : null}\n"""
text = replace_once(text, condition_block, condition_block + """        {entry.downed && showDeathSaves ? (\n          <div className=\"mt-2 rounded-lg border border-danger/40 bg-danger/10 p-2\">\n            <DeathSaveCounter entry={entry} editable={editDeathSaves} onChange={onDeathSaves} />\n          </div>\n        ) : null}\n""", "player death save counter")
write(path, text)

print("initiative identity/death-saves continuation applied")
