const FEATURE_NAMES_PT: Record<string, string> = {
  // Progressão geral
  "Ability Score Improvement": "Aprimoramento de Atributo",
  Spellcasting: "Conjuração",
  "Extra Attack": "Ataque Extra",
  "Extra Attack Improvement": "Aprimoramento de Ataque Extra",
  "Fighting Style": "Estilo de Luta",
  "Additional Fighting Style": "Estilo de Luta Adicional",
  Expertise: "Especialização",
  "Bonus Proficiencies": "Proficiências Adicionais",
  "Bonus Proficiency": "Proficiência Adicional",
  "Bonus Cantrip": "Truque Adicional",
  "Bonus Cantrips": "Truques Adicionais",
  "Channel Divinity": "Canalizar Divindade",
  "Channel Divinity Improvement": "Aprimoramento de Canalizar Divindade",
  "Cantrip Versatility": "Versatilidade de Truques",
  "Martial Versatility": "Versatilidade Marcial",
  "Sorcerous Versatility": "Versatilidade de Feiticeiro",
  "Eldritch Versatility": "Versatilidade Mística",
  "Harness Divine Power": "Canalizar Poder Divino",
  "Mystic Arcanum (6th level)": "Arcana Mística de 6º Nível",
  "Mystic Arcanum (7th level)": "Arcana Mística de 7º Nível",
  "Mystic Arcanum (8th level)": "Arcana Mística de 8º Nível",
  "Mystic Arcanum (9th level)": "Arcana Mística de 9º Nível",

  // Artífice
  "Magical Tinkering": "Engenhocas Mágicas",
  "Infuse Item": "Infundir Item",
  "Artificer Specialist": "Especialista Artífice",
  "The Right Tool for the Job": "A Ferramenta Certa para o Trabalho",
  "Specialist Feature": "Característica de Especialista",
  "Tool Expertise": "Especialização em Ferramentas",
  "Flash of Genius": "Centelha de Gênio",
  "Magic Item Adept": "Adepto de Itens Mágicos",
  "Spell-Storing Item": "Item Armazenador de Magia",
  "Magic Item Savant": "Especialista em Itens Mágicos",
  "Magic Item Master": "Mestre de Itens Mágicos",
  "Soul of Artifice": "Alma do Artífice",
  "Tool Proficiency": "Proficiência com Ferramentas",
  "Alchemist Spells": "Magias de Alquimista",
  "Experimental Elixir": "Elixir Experimental",
  "Alchemical Savant": "Sábio Alquímico",
  "Restorative Reagents": "Reagentes Restauradores",
  "Chemical Mastery": "Mestria Química",
  "Tools of the Trade": "Ferramentas do Ofício",
  "Armorer Spells": "Magias de Armeiro",
  "Arcane Armor": "Armadura Arcana",
  "Armor Model": "Modelo de Armadura",
  "Armor Modifications": "Modificações de Armadura",
  "Perfected Armor": "Armadura Aperfeiçoada",
  "Artillerist Spells": "Magias de Artilheiro",
  "Eldritch Cannon": "Canhão Místico",
  "Arcane Firearm": "Arma de Fogo Arcana",
  "Explosive Cannon": "Canhão Explosivo",
  "Fortified Position": "Posição Fortificada",
  "Battle Smith Spells": "Magias de Ferreiro de Batalha",
  "Battle Ready": "Pronto para a Batalha",
  "Steel Defender": "Defensor de Aço",
  "Arcane Jolt": "Impulso Arcano",
  "Improved Defender": "Defensor Aprimorado",

  // Bárbaro
  Rage: "Fúria",
  "Unarmored Defense": "Defesa sem Armadura",
  "Reckless Attack": "Ataque Imprudente",
  "Danger Sense": "Sentido de Perigo",
  "Primal Path": "Caminho Primal",
  "Primal Knowledge": "Conhecimento Primal",
  "Fast Movement": "Movimento Rápido",
  "Feral Instinct": "Instinto Selvagem",
  "Instinctive Pounce": "Bote Instintivo",
  "Brutal Critical": "Crítico Brutal",
  "Brutal Critical Improvement": "Aprimoramento de Crítico Brutal",
  "Relentless Rage": "Fúria Implacável",
  "Persistent Rage": "Fúria Persistente",
  "Indomitable Might": "Poder Indomável",
  "Primal Champion": "Campeão Primal",
  Frenzy: "Frenesi",
  "Mindless Rage": "Fúria Irracional",
  "Intimidating Presence": "Presença Intimidante",
  Retaliation: "Retaliação",
  "Spirit Seeker": "Buscador Espiritual",
  "Totem Spirit": "Espírito Totêmico",
  "Aspect of the Beast": "Aspecto da Besta",
  "Spirit Walker": "Andarilho Espiritual",
  "Totemic Attunement": "Sintonia Totêmica",
  "Form of the Beast": "Forma da Besta",
  "Bestial Soul": "Alma Bestial",
  "Infectious Fury": "Fúria Infecciosa",
  "Call the Hunt": "Chamado da Caçada",
  "Magic Awareness": "Percepção Mágica",
  "Wild Surge": "Surto Selvagem",
  "Bolstering Magic": "Magia Revigorante",
  "Unstable Backlash": "Reação Instável",
  "Controlled Surge": "Surto Controlado",
  "Ancestral Protectors": "Protetores Ancestrais",
  "Spirit Shield": "Escudo Espiritual",
  "Consult the Spirits": "Consultar os Espíritos",
  "Vengeful Ancestors": "Ancestrais Vingativos",
  "Storm Aura": "Aura da Tempestade",
  "Storm Soul": "Alma da Tempestade",
  "Shielding Storm": "Tempestade Protetora",
  "Raging Storm": "Tempestade Furiosa",
  "Divine Fury": "Fúria Divina",
  "Warrior of the Gods": "Guerreiro dos Deuses",
  "Fanatical Focus": "Foco Fanático",
  "Zealous Presence": "Presença Zelosa",
  "Rage Beyond Death": "Fúria Além da Morte",

  // Bardo
  "Bardic Inspiration": "Inspiração de Bardo",
  "Jack of All Trades": "Pau para Toda Obra",
  "Song of Rest": "Canção de Descanso",
  "Magical Inspiration": "Inspiração Mágica",
  "Bard College": "Colégio de Bardo",
  "Bardic Versatility": "Versatilidade de Bardo",
  "Font of Inspiration": "Fonte de Inspiração",
  "Bardic Inspiration Improvement": "Aprimoramento da Inspiração de Bardo",
  Countercharm: "Contraencanto",
  "Song of Rest Improvement": "Aprimoramento da Canção de Descanso",
  "Magical Secrets": "Segredos Mágicos",
  "Superior Inspiration": "Inspiração Superior",
  "Cutting Words": "Palavras Cortantes",
  "Additional Magical Secrets": "Segredos Mágicos Adicionais",
  "Peerless Skill": "Perícia Incomparável",
  "Combat Inspiration": "Inspiração em Combate",
  "Battle Magic": "Magia de Batalha",
  "Mote of Potential": "Centelha de Potencial",
  "Performance of Creation": "Atuação da Criação",
  "Animating Performance": "Atuação Animadora",
  "Creative Crescendo": "Crescendo Criativo",
  "Silver Tongue": "Língua de Prata",
  "Unsettling Words": "Palavras Perturbadoras",
  "Unfailing Inspiration": "Inspiração Infalível",
  "Universal Speech": "Fala Universal",
  "Infectious Inspiration": "Inspiração Infecciosa",
  "Mantle of Inspiration": "Manto da Inspiração",
  "Enthralling Performance": "Atuação Cativante",
  "Mantle of Majesty": "Manto da Majestade",
  "Unbreakable Majesty": "Majestade Inquebrável",
  "Blade Flourish": "Floreio de Lâmina",
  "Master's Flourish": "Floreio do Mestre",
  "Psychic Blades": "Lâminas Psíquicas",
  "Words of Terror": "Palavras de Terror",
  "Mantle of Whispers": "Manto de Sussurros",
  "Shadow Lore": "Conhecimento Sombrio",

  // Clérigo
  "Divine Domain": "Domínio Divino",
  "Turn Undead": "Expulsar Mortos-Vivos",
  "Destroy Undead": "Destruir Mortos-Vivos",
  "Destroy Undead Improvement": "Aprimoramento de Destruir Mortos-Vivos",
  "Blessed Strikes": "Golpes Abençoados",
  "Divine Intervention": "Intervenção Divina",
  "Improved Divine Intervention": "Intervenção Divina Aprimorada",
  "Blessings of Knowledge": "Bênçãos do Conhecimento",
  "Knowledge of the Ages": "Conhecimento das Eras",
  "Read Thoughts": "Ler Pensamentos",
  "Potent Spellcasting": "Conjuração Potente",
  "Visions of the Past": "Visões do Passado",
  "Disciple of Life": "Discípulo da Vida",
  "Preserve Life": "Preservar a Vida",
  "Blessed Healer": "Curandeiro Abençoado",
  "Divine Strike": "Golpe Divino",
  "Supreme Healing": "Cura Suprema",
  "Warding Flare": "Clarão Protetor",
  "Radiance of the Dawn": "Radiância da Aurora",
  "Improved Flare": "Clarão Aprimorado",
  "Corona of Light": "Coroa de Luz",
  "Acolyte of Nature": "Acólito da Natureza",
  "Charm Animals and Plants": "Encantar Animais e Plantas",
  "Dampen Elements": "Amortecer Elementos",
  "Master of Nature": "Mestre da Natureza",
  "Wrath of the Storm": "Ira da Tempestade",
  "Destructive Wrath": "Ira Destrutiva",
  "Thunderbolt Strike": "Golpe Trovejante",
  Stormborn: "Nascido da Tempestade",
  "Blessing of the Trickster": "Bênção do Trapaceiro",
  "Invoke Duplicity": "Invocar Duplicidade",
  "Cloak of Shadows": "Manto de Sombras",
  "Improved Duplicity": "Duplicidade Aprimorada",
  "War Priest": "Sacerdote da Guerra",
  "Guided Strike": "Golpe Guiado",
  "War God's Blessing": "Bênção do Deus da Guerra",
  "Avatar of Battle": "Avatar da Batalha",
  "Voice of Authority": "Voz da Autoridade",
  "Order's Demand": "Exigência da Ordem",
  "Embodiment of the Law": "Encarnação da Lei",
  "Order's Wrath": "Ira da Ordem",
  "Implement of Peace": "Instrumento da Paz",
  "Emboldening Bond": "Vínculo Encorajador",
  "Balm of Peace": "Bálsamo da Paz",
  "Protective Bond": "Vínculo Protetor",
  "Expansive Bond": "Vínculo Expansivo",
  "Eyes of Night": "Olhos da Noite",
  "Vigilant Blessing": "Bênção Vigilante",
  "Twilight Sanctuary": "Santuário do Crepúsculo",
  "Steps of Night": "Passos da Noite",
  "Twilight Shroud": "Mortalha do Crepúsculo",
  "Blessing of the Forge": "Bênção da Forja",
  "Artisan's Blessing": "Bênção do Artesão",
  "Soul of the Forge": "Alma da Forja",
  "Saint of Forge and Fire": "Santo da Forja e do Fogo",
  "Circle of Mortality": "Círculo da Mortalidade",
  "Eyes of the Grave": "Olhos da Sepultura",
  "Path to the Grave": "Caminho para a Sepultura",
  "Sentinel at Death's Door": "Sentinela às Portas da Morte",
  "Keeper of Souls": "Guardião das Almas",

  // Druida
  Druidic: "Druídico",
  "Wild Shape": "Forma Selvagem",
  "Druid Circle": "Círculo Druídico",
  "Wild Companion": "Companheiro Selvagem",
  "Wild Shape Improvement": "Aprimoramento da Forma Selvagem",
  "Timeless Body": "Corpo Atemporal",
  "Beast Spells": "Magias Bestiais",
  Archdruid: "Arquiduida",
  "Natural Recovery": "Recuperação Natural",
  "Circle Spells": "Magias do Círculo",
  "Land's Stride": "Passo da Terra",
  "Nature's Ward": "Proteção da Natureza",
  "Nature's Sanctuary": "Santuário da Natureza",
  "Combat Wild Shape": "Forma Selvagem de Combate",
  "Circle Forms": "Formas do Círculo",
  "Primal Strike": "Golpe Primal",
  "Elemental Wild Shape": "Forma Selvagem Elemental",
  "Thousand Forms": "Mil Formas",
  "Halo of Spores": "Halo de Esporos",
  "Symbiotic Entity": "Entidade Simbiótica",
  "Fungal Infestation": "Infestação Fúngica",
  "Spreading Spores": "Esporos Disseminados",
  "Fungal Body": "Corpo Fúngico",
  "Star Map": "Mapa Estelar",
  "Starry Form": "Forma Estrelada",
  "Cosmic Omen": "Presságio Cósmico",
  "Twinkling Constellations": "Constelações Cintilantes",
  "Full of Stars": "Repleto de Estrelas",
  "Summon Wildfire Spirit": "Invocar Espírito do Fogo Selvagem",
  "Enhanced Bond": "Vínculo Aprimorado",
  "Cauterizing Flames": "Chamas Cauterizantes",
  "Blazing Revival": "Renascimento Ardente",
  "Balm of the Summer Court": "Bálsamo da Corte de Verão",
  "Hearth of Moonlight and Shadow": "Lar de Luar e Sombra",
  "Hidden Paths": "Caminhos Ocultos",
  "Walker in Dreams": "Andarilho dos Sonhos",
  "Speech of the Woods": "Fala dos Bosques",
  "Spirit Totem": "Totem Espiritual",
  "Mighty Summoner": "Invocador Poderoso",
  "Guardian Spirit": "Espírito Guardião",
  "Faithful Summons": "Invocações Fiéis",

  // Guerreiro
  "Second Wind": "Retomar o Fôlego",
  "Action Surge": "Surto de Ação",
  "Martial Archetype": "Arquétipo Marcial",
  Indomitable: "Indomável",
  "Indomitable Improvement": "Aprimoramento de Indomável",
  "Improved Critical": "Crítico Aprimorado",
  "Remarkable Athlete": "Atleta Excepcional",
  "Superior Critical": "Crítico Superior",
  Survivor: "Sobrevivente",
  "Combat Superiority": "Superioridade em Combate",
  "Student of War": "Estudante da Guerra",
  "Know Your Enemy": "Conheça seu Inimigo",
  "Improved Combat Superiority": "Superioridade em Combate Aprimorada",
  Relentless: "Implacável",
  "Weapon Bond": "Vínculo com Arma",
  "War Magic": "Magia de Guerra",
  "Eldritch Strike": "Golpe Místico",
  "Arcane Charge": "Carga Arcana",
  "Improved War Magic": "Magia de Guerra Aprimorada",
  "Psionic Power": "Poder Psiônico",
  "Telekinetic Adept": "Adepto Telecinético",
  "Guarded Mind": "Mente Protegida",
  "Bulwark of Force": "Baluarte de Força",
  "Telekinetic Master": "Mestre Telecinético",
  "Rune Carver": "Gravador de Runas",
  "Giant's Might": "Poder do Gigante",
  "Runic Shield": "Escudo Rúnico",
  "Great Stature": "Grande Estatura",
  "Master of Runes": "Mestre das Runas",
  "Runic Juggernaut": "Colosso Rúnico",
  "Arcane Archer Lore": "Conhecimento do Arqueiro Arcano",
  "Arcane Shot": "Disparo Arcano",
  "Magic Arrow": "Flecha Mágica",
  "Curving Shot": "Disparo Curvo",
  "Additional Arcane Shot Option": "Opção Adicional de Disparo Arcano",
  "Ever-Ready Shot": "Disparo Sempre Pronto",
  "Born to the Saddle": "Nascido na Sela",
  "Unwavering Mark": "Marca Inabalável",
  "Warding Maneuver": "Manobra Protetora",
  "Hold the Line": "Manter a Linha",
  "Ferocious Charger": "Investida Feroz",
  "Vigilant Defender": "Defensor Vigilante",
  "Fighting Spirit": "Espírito de Luta",
  "Elegant Courtier": "Cortesão Elegante",
  "Tireless Spirit": "Espírito Incansável",
  "Rapid Strike": "Golpe Rápido",
  "Strength Before Death": "Força Antes da Morte",

  // Monge
  "Martial Arts": "Artes Marciais",
  Ki: "Ki",
  "Unarmored Movement": "Movimento sem Armadura",
  "Dedicated Weapon": "Arma Dedicada",
  "Monastic Tradition": "Tradição Monástica",
  "Deflect Missiles": "Desviar Projéteis",
  "Ki-Fueled Attack": "Ataque Impulsionado por Ki",
  "Slow Fall": "Queda Lenta",
  "Quickened Healing": "Cura Acelerada",
  "Stunning Strike": "Golpe Atordoante",
  "Focused Aim": "Mira Focada",
  "Ki-Empowered Strikes": "Golpes Fortalecidos por Ki",
  Evasion: "Evasão",
  "Stillness of Mind": "Serenidade da Mente",
  "Unarmored Movement Improvement": "Aprimoramento de Movimento sem Armadura",
  "Purity of Body": "Pureza Corporal",
  "Tongue of the Sun and Moon": "Língua do Sol e da Lua",
  "Diamond Soul": "Alma de Diamante",
  "Empty Body": "Corpo Vazio",
  "Perfect Self": "Perfeição de Si",
  "Open Hand Technique": "Técnica da Mão Aberta",
  "Wholeness of Body": "Integridade Corporal",
  Tranquility: "Tranquilidade",
  "Quivering Palm": "Palma Vibrante",
  "Shadow Arts": "Artes das Sombras",
  "Shadow Step": "Passo das Sombras",
  "Cloak of Shadows": "Manto de Sombras",
  Opportunist: "Oportunista",
  "Disciple of the Elements": "Discípulo dos Elementos",
  "Additional Elemental Discipline": "Disciplina Elemental Adicional",
  "Arms of the Astral Self": "Braços do Eu Astral",
  "Visage of the Astral Self": "Semblante do Eu Astral",
  "Body of the Astral Self": "Corpo do Eu Astral",
  "Awakened Astral Self": "Eu Astral Desperto",
  "Implements of Mercy": "Instrumentos da Misericórdia",
  "Hand of Healing": "Mão da Cura",
  "Hand of Harm": "Mão do Dano",
  "Physician's Touch": "Toque do Médico",
  "Flurry of Healing and Harm": "Rajada de Cura e Dano",
  "Hand of Ultimate Mercy": "Mão da Misericórdia Suprema",
  "Drunken Technique": "Técnica Bêbada",
  "Tipsy Sway": "Oscilação Embriagada",
  "Drunkard's Luck": "Sorte do Bêbado",
  "Intoxicated Frenzy": "Frenesi Embriagado",
  "Path of the Kensei": "Caminho do Kensei",
  "One with the Blade": "Uno com a Lâmina",
  "Sharpen the Blade": "Afiar a Lâmina",
  "Unerring Accuracy": "Precisão Infalível",
  "Radiant Sun Bolt": "Raio Solar Radiante",
  "Searing Arc Strike": "Golpe de Arco Flamejante",
  "Searing Sunburst": "Explosão Solar Ardente",
  "Sun Shield": "Escudo Solar",

  // Paladino
  "Divine Sense": "Sentido Divino",
  "Lay on Hands": "Cura pelas Mãos",
  "Divine Smite": "Destruição Divina",
  "Divine Health": "Saúde Divina",
  "Sacred Oath": "Juramento Sagrado",
  "Aura of Protection": "Aura de Proteção",
  "Aura of Courage": "Aura de Coragem",
  "Improved Divine Smite": "Destruição Divina Aprimorada",
  "Cleansing Touch": "Toque Purificador",
  "Aura Improvements": "Aprimoramento das Auras",
  "Oath Spells": "Magias de Juramento",
  "Sacred Weapon": "Arma Sagrada",
  "Turn the Unholy": "Expulsar Profanos",
  "Aura of Devotion": "Aura de Devoção",
  "Purity of Spirit": "Pureza de Espírito",
  "Holy Nimbus": "Nimbo Sagrado",
  "Nature's Wrath": "Ira da Natureza",
  "Turn the Faithless": "Expulsar os Infiéis",
  "Aura of Warding": "Aura de Proteção Mística",
  "Undying Sentinel": "Sentinela Imortal",
  "Elder Champion": "Campeão Ancião",
  "Abjure Enemy": "Abjurar Inimigo",
  "Vow of Enmity": "Voto de Inimizade",
  "Relentless Avenger": "Vingador Implacável",
  "Soul of Vengeance": "Alma da Vingança",
  "Avenging Angel": "Anjo Vingador",
  "Peerless Athlete": "Atleta Inigualável",
  "Inspiring Smite": "Destruição Inspiradora",
  "Aura of Alacrity": "Aura de Vivacidade",
  "Glorious Defense": "Defesa Gloriosa",
  "Living Legend": "Lenda Viva",
  "Watcher's Will": "Vontade do Vigilante",
  "Abjure the Extraplanar": "Abjurar o Extraplanar",
  "Aura of the Sentinel": "Aura da Sentinela",
  "Vigilant Rebuke": "Repreensão Vigilante",
  "Mortal Bulwark": "Baluarte Mortal",
  "Conquering Presence": "Presença Conquistadora",
  "Aura of Conquest": "Aura de Conquista",
  "Scornful Rebuke": "Repreensão Desdenhosa",
  "Invincible Conqueror": "Conquistador Invencível",
  "Emissary of Peace": "Emissário da Paz",
  "Rebuke the Violent": "Repreender os Violentos",
  "Aura of the Guardian": "Aura do Guardião",
  "Protective Spirit": "Espírito Protetor",
  "Emissary of Redemption": "Emissário da Redenção",

  // Patrulheiro
  "Favored Enemy": "Inimigo Favorito",
  "Natural Explorer": "Explorador Natural",
  "Deft Explorer": "Explorador Hábil",
  "Favored Foe": "Inimigo Marcado",
  "Spellcasting Focus": "Foco de Conjuração",
  "Ranger Archetype": "Arquétipo de Patrulheiro",
  "Primeval Awareness": "Consciência Primitiva",
  "Primal Awareness": "Consciência Primal",
  "Favored Enemy Improvement": "Aprimoramento de Inimigo Favorito",
  "Natural Explorer Improvement": "Aprimoramento de Explorador Natural",
  "Hide in Plain Sight": "Esconder-se à Vista",
  "Nature's Veil": "Véu da Natureza",
  Vanish: "Desaparecer",
  "Feral Senses": "Sentidos Selvagens",
  "Foe Slayer": "Matador de Inimigos",
  "Hunter's Prey": "Presa do Caçador",
  "Defensive Tactics": "Táticas Defensivas",
  Multiattack: "Ataque Múltiplo",
  "Superior Hunter's Defense": "Defesa Superior do Caçador",
  "Ranger's Companion": "Companheiro do Patrulheiro",
  "Primal Companion": "Companheiro Primal",
  "Exceptional Training": "Treinamento Excepcional",
  "Bestial Fury": "Fúria Bestial",
  "Share Spells": "Compartilhar Magias",
  "Dreadful Strikes": "Golpes Terríveis",
  "Fey Wanderer Magic": "Magia do Andarilho Feérico",
  "Otherworldly Glamour": "Glamour Sobrenatural",
  "Beguiling Twist": "Reviravolta Encantadora",
  "Fey Reinforcements": "Reforços Feéricos",
  "Misty Wanderer": "Andarilho Nebuloso",
  "Gathered Swarm": "Enxame Reunido",
  "Swarmkeeper Magic": "Magia do Guardião do Enxame",
  "Writhing Tide": "Maré Contorcida",
  "Mighty Swarm": "Enxame Poderoso",
  "Swarming Dispersal": "Dispersão do Enxame",
  "Gloom Stalker Magic": "Magia do Espreitador Sombrio",
  "Dread Ambusher": "Emboscador Temível",
  "Umbral Sight": "Visão Umbral",
  "Iron Mind": "Mente de Ferro",
  "Stalker's Flurry": "Rajada do Espreitador",
  "Shadowy Dodge": "Esquiva Sombria",
  "Horizon Walker Magic": "Magia do Andarilho do Horizonte",
  "Detect Portal": "Detectar Portal",
  "Planar Warrior": "Guerreiro Planar",
  "Ethereal Step": "Passo Etéreo",
  "Distant Strike": "Golpe Distante",
  "Spectral Defense": "Defesa Espectral",
  "Monster Slayer Magic": "Magia do Matador de Monstros",
  "Hunter's Sense": "Sentido do Caçador",
  "Slayer's Prey": "Presa do Matador",
  "Supernatural Defense": "Defesa Sobrenatural",
  "Magic-User's Nemesis": "Nêmesis do Usuário de Magia",
  "Slayer's Counter": "Contra-Ataque do Matador",

  // Ladino
  "Sneak Attack": "Ataque Furtivo",
  "Thieves' Cant": "Gíria de Ladrão",
  "Cunning Action": "Ação Ardilosa",
  "Roguish Archetype": "Arquétipo de Ladino",
  "Steady Aim": "Mira Firme",
  "Uncanny Dodge": "Esquiva Sobrenatural",
  "Reliable Talent": "Talento Confiável",
  Blindsense: "Sentido Cego",
  "Slippery Mind": "Mente Escorregadia",
  Elusive: "Elusivo",
  "Stroke of Luck": "Golpe de Sorte",
  "Fast Hands": "Mãos Rápidas",
  "Second-Story Work": "Trabalho em Altura",
  "Supreme Sneak": "Furtividade Suprema",
  "Use Magic Device": "Usar Dispositivo Mágico",
  "Thief's Reflexes": "Reflexos de Ladrão",
  Assassinate: "Assassinar",
  "Infiltration Expertise": "Especialização em Infiltração",
  Impostor: "Impostor",
  "Death Strike": "Golpe Mortal",
  "Mage Hand Legerdemain": "Prestidigitação com Mão Mágica",
  "Magical Ambush": "Emboscada Mágica",
  "Versatile Trickster": "Trapaceiro Versátil",
  "Spell Thief": "Ladrão de Magias",
  "Whispers of the Dead": "Sussurros dos Mortos",
  "Wails from the Grave": "Lamentos da Sepultura",
  "Tokens of the Departed": "Símbolos dos Falecidos",
  "Ghost Walk": "Caminhada Fantasma",
  "Death's Friend": "Amigo da Morte",
  "Soul Blades": "Lâminas da Alma",
  "Psychic Veil": "Véu Psíquico",
  "Rend Mind": "Dilacerar Mente",
  "Ear for Deceit": "Ouvido para Enganação",
  "Eye for Detail": "Olho para Detalhes",
  "Insightful Fighting": "Combate Perspicaz",
  "Steady Eye": "Olhar Firme",
  "Unerring Eye": "Olhar Infalível",
  "Eye for Weakness": "Olho para Fraquezas",
  "Master of Intrigue": "Mestre da Intriga",
  "Master of Tactics": "Mestre das Táticas",
  "Insightful Manipulator": "Manipulador Perspicaz",
  Misdirection: "Desorientação",
  "Soul of Deceit": "Alma da Enganação",
  Skirmisher: "Escaramuçador",
  Survivalist: "Sobrevivencialista",
  "Superior Mobility": "Mobilidade Superior",
  "Ambush Master": "Mestre da Emboscada",
  "Sudden Strike": "Golpe Súbito",
  "Fancy Footwork": "Passos Elegantes",
  "Rakish Audacity": "Audácia Galante",
  Panache: "Bravata",
  "Elegant Maneuver": "Manobra Elegante",
  "Master Duelist": "Mestre Duelista",

  // Feiticeiro
  "Sorcerous Origin": "Origem de Feitiçaria",
  "Font of Magic": "Fonte de Magia",
  Metamagic: "Metamagia",
  "Sorcerous Origin Feature": "Característica da Origem de Feitiçaria",
  "Sorcerous Restoration": "Restauração de Feitiçaria",
  "Dragon Ancestor": "Ancestral Dracônico",
  "Draconic Resilience": "Resiliência Dracônica",
  "Elemental Affinity": "Afinidade Elemental",
  "Dragon Wings": "Asas de Dragão",
  "Draconic Presence": "Presença Dracônica",
  "Wild Magic Surge": "Surto de Magia Selvagem",
  "Tides of Chaos": "Marés do Caos",
  "Bend Luck": "Dobrar a Sorte",
  "Controlled Chaos": "Caos Controlado",
  "Spell Bombardment": "Bombardeio Mágico",
  "Psionic Spells": "Magias Psiônicas",
  "Telepathic Speech": "Fala Telepática",
  "Psionic Sorcery": "Feitiçaria Psiônica",
  "Psychic Defenses": "Defesas Psíquicas",
  "Revelation in Flesh": "Revelação na Carne",
  "Warping Implosion": "Implosão Distorcida",
  "Clockwork Magic": "Magia Mecânica",
  "Restore Balance": "Restaurar Equilíbrio",
  "Bastion of Law": "Bastião da Lei",
  "Trance of Order": "Transe da Ordem",
  "Clockwork Cavalcade": "Cavalcada Mecânica",
  "Divine Magic": "Magia Divina",
  "Favored by the Gods": "Favorecido pelos Deuses",
  "Empowered Healing": "Cura Fortalecida",
  "Otherworldly Wings": "Asas Sobrenaturais",
  "Unearthly Recovery": "Recuperação Sobrenatural",
  "Eyes of the Dark": "Olhos do Escuro",
  "Strength of the Grave": "Força da Sepultura",
  "Hound of Ill Omen": "Cão do Mau Agouro",
  "Shadow Walk": "Caminhada Sombria",
  "Umbral Form": "Forma Umbral",
  "Wind Speaker": "Orador dos Ventos",
  "Tempestuous Magic": "Magia Tempestuosa",
  "Heart of the Storm": "Coração da Tempestade",
  "Storm Guide": "Guia da Tempestade",
  "Storm's Fury": "Fúria da Tempestade",
  "Wind Soul": "Alma do Vento",

  // Bruxo
  "Otherworldly Patron": "Patrono Transcendental",
  "Pact Magic": "Magia de Pacto",
  "Eldritch Invocations": "Invocações Místicas",
  "Pact Boon": "Dádiva do Pacto",
  "Additional Invocation": "Invocação Adicional",
  "Eldritch Master": "Mestre Místico",
  "Fey Presence": "Presença Feérica",
  "Misty Escape": "Fuga Nebulosa",
  "Beguiling Defenses": "Defesas Encantadoras",
  "Dark Delirium": "Delírio Sombrio",
  "Dark One's Blessing": "Bênção do Corruptor",
  "Dark One's Own Luck": "Sorte do Próprio Corruptor",
  "Fiendish Resilience": "Resiliência Diabólica",
  "Hurl Through Hell": "Arremessar pelo Inferno",
  "Awakened Mind": "Mente Desperta",
  "Entropic Ward": "Proteção Entrópica",
  "Thought Shield": "Escudo de Pensamento",
  "Create Thrall": "Criar Servo",
  "Expanded Spell List": "Lista de Magias Expandida",
  "Tentacle of the Deeps": "Tentáculo das Profundezas",
  "Gift of the Sea": "Dádiva do Mar",
  "Oceanic Soul": "Alma Oceânica",
  "Guardian Coil": "Espiral Guardiã",
  "Grasping Tentacles": "Tentáculos Agarradores",
  "Fathomless Plunge": "Mergulho Insondável",
  "Genie's Vessel": "Recipiente do Gênio",
  "Elemental Gift": "Dádiva Elemental",
  "Sanctuary Vessel": "Recipiente Santuário",
  "Limited Wish": "Desejo Limitado",
  "Healing Light": "Luz Curativa",
  "Radiant Soul": "Alma Radiante",
  "Celestial Resilience": "Resiliência Celestial",
  "Searing Vengeance": "Vingança Ardente",
  "Hexblade's Curse": "Maldição da Lâmina Maldita",
  "Hex Warrior": "Guerreiro da Lâmina Maldita",
  "Accursed Specter": "Espectro Amaldiçoado",
  "Armor of Hexes": "Armadura de Maldições",
  "Master of Hexes": "Mestre das Maldições",

  // Mago
  "Arcane Recovery": "Recuperação Arcana",
  "Arcane Tradition": "Tradição Arcana",
  "Cantrip Formulas": "Fórmulas de Truques",
  "Spell Mastery": "Domínio de Magias",
  "Signature Spells": "Magias de Assinatura",
  "Abjuration Savant": "Sábio da Abjuração",
  "Arcane Ward": "Proteção Arcana",
  "Projected Ward": "Proteção Projetada",
  "Improved Abjuration": "Abjuração Aprimorada",
  "Spell Resistance": "Resistência a Magia",
  "Conjuration Savant": "Sábio da Conjuração",
  "Minor Conjuration": "Conjuração Menor",
  "Benign Transposition": "Transposição Benigna",
  "Focused Conjuration": "Conjuração Focada",
  "Durable Summons": "Invocações Duráveis",
  "Divination Savant": "Sábio da Adivinhação",
  Portent: "Presságio",
  "Expert Divination": "Adivinhação Especializada",
  "The Third Eye": "O Terceiro Olho",
  "Greater Portent": "Presságio Maior",
  "Enchantment Savant": "Sábio do Encantamento",
  "Hypnotic Gaze": "Olhar Hipnótico",
  "Instinctive Charm": "Encanto Instintivo",
  "Split Enchantment": "Encantamento Dividido",
  "Alter Memories": "Alterar Memórias",
  "Evocation Savant": "Sábio da Evocação",
  "Sculpt Spells": "Esculpir Magias",
  "Potent Cantrip": "Truque Potente",
  "Empowered Evocation": "Evocação Fortalecida",
  Overchannel: "Sobrecarga",
  "Illusion Savant": "Sábio da Ilusão",
  "Improved Minor Illusion": "Ilusão Menor Aprimorada",
  "Malleable Illusions": "Ilusões Maleáveis",
  "Illusory Self": "Eu Ilusório",
  "Illusory Reality": "Realidade Ilusória",
  "Necromancy Savant": "Sábio da Necromancia",
  "Grim Harvest": "Colheita Sombria",
  "Undead Thralls": "Servos Mortos-Vivos",
  "Inured to Undeath": "Habituado à Não-Morte",
  "Command Undead": "Comandar Mortos-Vivos",
  "Transmutation Savant": "Sábio da Transmutação",
  "Minor Alchemy": "Alquimia Menor",
  "Transmuter's Stone": "Pedra do Transmutador",
  Shapechanger: "Metamorfo",
  "Master Transmuter": "Mestre Transmutador",
  "Training in War and Song": "Treinamento em Guerra e Canção",
  Bladesong: "Canto da Lâmina",
  "Song of Defense": "Canção de Defesa",
  "Song of Victory": "Canção da Vitória",
  "Wizardly Quill": "Pena de Mago",
  "Awakened Spellbook": "Grimório Desperto",
  "Manifest Mind": "Mente Manifestada",
  "Master Scrivener": "Mestre Escriba",
  "One with the Word": "Uno com a Palavra",
  "Arcane Deflection": "Deflexão Arcana",
  "Tactical Wit": "Astúcia Tática",
  "Power Surge": "Surto de Poder",
  "Durable Magic": "Magia Duradoura",
  "Deflecting Shroud": "Mortalha Defletora",
}

const CHOICE_LABELS_PT: Record<string, string> = {
  "Ability Score Improvement or feat": "Aprimoramento de atributo ou talento",
  "Fighting style": "Estilo de luta",
  "Additional fighting style": "Estilo de luta adicional",
  "Expertise skills": "Perícias para especialização",
  "Metamagic options": "Opções de metamagia",
  "Additional metamagic": "Metamagia adicional",
  "Pact boon": "Dádiva do pacto",
  "Eldritch invocations": "Invocações místicas",
  "Additional invocation": "Invocação adicional",
  Maneuvers: "Manobras",
  "Additional maneuvers": "Manobras adicionais",
  "Infusions known": "Infusões conhecidas",
  "Additional infusions": "Infusões adicionais",
  "Elemental disciplines": "Disciplinas elementais",
  "Elemental discipline": "Disciplina elemental",
  Runes: "Runas",
  "Additional rune": "Runa adicional",
  "Totem spirit": "Espírito totêmico",
  "Bestial aspect": "Aspecto bestial",
  "Totemic attunement": "Sintonia totêmica",
  "Land type": "Tipo de terreno",
  "Dragon ancestry": "Ancestral dracônico",
  "Genie kind": "Tipo de gênio",
  "Storm environment": "Ambiente da tempestade",
  "College of Swords fighting style": "Estilo de luta do Colégio das Espadas",
  "Arcane Shot options": "Opções de Disparo Arcano",
  "Additional Arcane Shot option": "Opção adicional de Disparo Arcano",
  "Initial kensei weapons": "Armas kensei iniciais",
  "Additional kensei weapon": "Arma kensei adicional",
  "Divine affinity": "Afinidade divina",
  "Hunter's Prey": "Presa do Caçador",
  "Defensive Tactics": "Táticas Defensivas",
  Multiattack: "Ataque Múltiplo",
  "Superior Hunter's Defense": "Defesa Superior do Caçador",
}

const OPTION_NAMES_PT: Record<string, string> = {
  Bear: "Urso",
  Eagle: "Águia",
  Wolf: "Lobo",
  Desert: "Deserto",
  Sea: "Mar",
  Tundra: "Tundra",
  Arctic: "Ártico",
  Coast: "Costa",
  Forest: "Floresta",
  Grassland: "Planície",
  Mountain: "Montanha",
  Swamp: "Pântano",
  Underdark: "Subterrâneo",
  Good: "Bem",
  Evil: "Mal",
  Law: "Ordem",
  Chaos: "Caos",
  Neutrality: "Neutralidade",
  Dueling: "Duelismo",
  Defense: "Defesa",
  Archery: "Arquearia",
  Protection: "Proteção",
  "Two-Weapon Fighting": "Combate com Duas Armas",
  "Great Weapon Fighting": "Combate com Armas Grandes",
  "Blind Fighting": "Combate às Cegas",
  Interception: "Intercepção",
  "Superior Technique": "Técnica Superior",
  "Thrown Weapon Fighting": "Combate com Armas de Arremesso",
  "Unarmed Fighting": "Combate Desarmado",
}

export function getFeatureNamePt(name: string): string {
  return FEATURE_NAMES_PT[name] ?? name
}

export function getChoiceLabelPt(label: string): string {
  return CHOICE_LABELS_PT[label] ?? label
}

export function getChoiceOptionPt(option: string): string {
  return OPTION_NAMES_PT[option] ?? option
}
