import type { ClassProgressionDefinition } from "./ClassProgression"
import type { ClassName } from "../sheet/Class"

const FEATURE_NAMES: Record<string, string> = {
  "Blessings of Knowledge": "Bênçãos do Conhecimento",
  "Knowledge of the Ages": "Conhecimento das Eras",
  "Read Thoughts": "Ler Pensamentos",
  "Visions of the Past": "Visões do Passado",
  "Charm Animals and Plants": "Encantar Animais e Plantas",
  "Nature's Ward": "Proteção da Natureza",
  "Nature's Sanctuary": "Santuário da Natureza",
  "Voice of Authority": "Voz da Autoridade",
  "Order's Demand": "Exigência da Ordem",
  "Embodiment of the Law": "Encarnação da Lei",
  "Order's Wrath": "Ira da Ordem",
  "Implement of Peace": "Instrumento da Paz",
  "Emboldening Bond": "Vínculo Encorajador",
  "Balm of Peace": "Bálsamo da Paz",
  "Protective Bond": "Vínculo Protetor",
  "Expansive Bond": "Vínculo Expansivo",
  "Eyes of Night": "Olhos da Noite",
  "Vigilant Blessing": "Bênção Vigilante",
  "Twilight Sanctuary": "Santuário do Crepúsculo",
  "Steps of Night": "Passos da Noite",
  "Twilight Shroud": "Manto do Crepúsculo",
  "Hunter's Prey": "Presa do Caçador",
  "Defensive Tactics": "Táticas Defensivas",
  "Multiattack": "Ataque Múltiplo",
  "Superior Hunter's Defense": "Defesa Superior do Caçador",
  "Ranger's Companion": "Companheiro do Patrulheiro",
  "Primal Companion": "Companheiro Primordial",
  "Exceptional Training": "Treinamento Excepcional",
  "Bestial Fury": "Fúria Bestial",
  "Share Spells": "Compartilhar Magias",
  "Dreadful Strikes": "Golpes Aterradores",
  "Fey Wanderer Magic": "Magia do Andarilho Feérico",
  "Otherworldly Glamour": "Glamour Transcendental",
  "Beguiling Twist": "Desvio Sedutor",
  "Fey Reinforcements": "Reforços Feéricos",
  "Misty Wanderer": "Andarilho Enevoado",
  "Gathered Swarm": "Enxame Reunido",
  "Swarmkeeper Magic": "Magia do Guardião de Enxame",
  "Writhing Tide": "Maré Contorcida",
  "Mighty Swarm": "Enxame Poderoso",
  "Swarming Dispersal": "Dispersão do Enxame",
  "Fast Hands": "Mãos Rápidas",
  "Second-Story Work": "Trabalho em Altura",
  "Supreme Sneak": "Furtividade Suprema",
  "Use Magic Device": "Usar Dispositivo Mágico",
  "Thief's Reflexes": "Reflexos de Ladrão",
  "Assassinate": "Assassinar",
  "Infiltration Expertise": "Especialização em Infiltração",
  "Impostor": "Impostor",
  "Death Strike": "Golpe Mortal",
  "Mage Hand Legerdemain": "Prestidigitação com Mãos Mágicas",
  "Magical Ambush": "Emboscada Mágica",
  "Versatile Trickster": "Trapaceiro Versátil",
  "Spell Thief": "Ladrão de Magias",
  "Whispers of the Dead": "Sussurros dos Mortos",
  "Wails from the Grave": "Lamentos da Sepultura",
  "Tokens of the Departed": "Símbolos dos Falecidos",
  "Ghost Walk": "Caminhada Fantasma",
  "Death's Friend": "Amigo da Morte",
  "Psychic Blades": "Lâminas Psíquicas",
  "Soul Blades": "Lâminas da Alma",
  "Psychic Veil": "Véu Psíquico",
  "Rend Mind": "Dilacerar Mente",
  "Dragon Ancestor": "Ancestral Dracônico",
  "Draconic Resilience": "Resiliência Dracônica",
  "Elemental Affinity": "Afinidade Elemental",
  "Dragon Wings": "Asas de Dragão",
  "Draconic Presence": "Presença Dracônica",
  "Expanded Spell List": "Lista de Magias Expandida",
  "Healing Light": "Luz Curativa",
  "Radiant Soul": "Alma Radiante",
  "Celestial Resilience": "Resiliência Celestial",
  "Searing Vengeance": "Vingança Ardente",
  "Genie's Vessel": "Recipiente do Gênio",
  "Elemental Gift": "Dádiva Elemental",
  "Sanctuary Vessel": "Recipiente Santuário",
  "Limited Wish": "Desejo Limitado",
  "Bottled Respite": "Repouso Engarrafado",
  "Tentacle of the Deeps": "Tentáculo das Profundezas",
  "Gift of the Sea": "Dádiva do Mar",
  "Oceanic Soul": "Alma Oceânica",
  "Guardian Coil": "Espiral Guardiã",
  "Grasping Tentacles": "Tentáculos Agarradores",
  "Fathomless Plunge": "Mergulho Insondável",
  "Sculpt Spells": "Esculpir Magias",
  "Potent Cantrip": "Truque Potente",
  "Empowered Evocation": "Evocação Fortalecida",
  "Overchannel": "Sobrecarga",
  "Portent": "Presságio",
  "Expert Divination": "Adivinhação Especializada",
  "The Third Eye": "O Terceiro Olho",
  "Greater Portent": "Presságio Maior",
  "Hypnotic Gaze": "Olhar Hipnótico",
  "Instinctive Charm": "Encanto Instintivo",
  "Split Enchantment": "Encantamento Dividido",
  "Alter Memories": "Alterar Memórias",
  "Minor Conjuration": "Conjuração Menor",
  "Benign Transposition": "Transposição Benigna",
  "Focused Conjuration": "Conjuração Focada",
  "Durable Summons": "Invocações Duráveis",
  "Ancestral Protectors": "Protetores Ancestrais",
  "Spirit Shield": "Escudo Espiritual",
  "Consult the Spirits": "Consultar os Espíritos",
  "Vengeful Ancestors": "Ancestrais Vingativos",
  "Storm Aura": "Aura da Tempestade",
  "Storm Soul": "Alma da Tempestade",
  "Shielding Storm": "Tempestade Protetora",
  "Raging Storm": "Tempestade Furiosa",
  "Divine Fury": "Fúria Divina",
  "Warrior of the Gods": "Guerreiro dos Deuses",
  "Fanatical Focus": "Foco Fanático",
  "Zealous Presence": "Presença Zelosa",
  "Rage Beyond Death": "Fúria Além da Morte",
  "Mantle of Inspiration": "Manto de Inspiração",
  "Enthralling Performance": "Atuação Cativante",
  "Mantle of Majesty": "Manto de Majestade",
  "Unbreakable Majesty": "Majestade Inquebrável",
  "Blade Flourish": "Floreio de Lâmina",
  "Master's Flourish": "Floreio do Mestre",
  "Words of Terror": "Palavras de Terror",
  "Mantle of Whispers": "Manto de Sussurros",
  "Shadow Lore": "Conhecimento Sombrio",
  "Blessing of the Forge": "Bênção da Forja",
  "Artisan's Blessing": "Bênção do Artesão",
  "Soul of the Forge": "Alma da Forja",
  "Saint of Forge and Fire": "Santo da Forja e do Fogo",
  "Circle of Mortality": "Círculo da Mortalidade",
  "Eyes of the Grave": "Olhos da Sepultura",
  "Path to the Grave": "Caminho para a Sepultura",
  "Sentinel at Death's Door": "Sentinela à Porta da Morte",
  "Keeper of Souls": "Guardião das Almas",
  "Balm of the Summer Court": "Bálsamo da Corte de Verão",
  "Hearth of Moonlight and Shadow": "Refúgio de Luar e Sombra",
  "Hidden Paths": "Caminhos Ocultos",
  "Walker in Dreams": "Caminhante dos Sonhos",
  "Speech of the Woods": "Fala das Florestas",
  "Spirit Totem": "Totem Espiritual",
  "Mighty Summoner": "Invocador Poderoso",
  "Guardian Spirit": "Espírito Guardião",
  "Faithful Summons": "Invocações Fiéis",
  "Arcane Archer Lore": "Conhecimento do Arqueiro Arcano",
  "Arcane Shot": "Disparo Arcano",
  "Magic Arrow": "Flecha Mágica",
  "Curving Shot": "Disparo Curvo",
  "Additional Arcane Shot Option": "Opção Adicional de Disparo Arcano",
  "Ever-Ready Shot": "Disparo Sempre Pronto",
  "Bonus Proficiency": "Proficiência Adicional",
  "Born to the Saddle": "Nascido para a Sela",
  "Unwavering Mark": "Marca Inabalável",
  "Warding Maneuver": "Manobra Protetora",
  "Hold the Line": "Manter a Linha",
  "Ferocious Charger": "Investida Feroz",
  "Vigilant Defender": "Defensor Vigilante",
  "Fighting Spirit": "Espírito de Luta",
  "Elegant Courtier": "Cortesão Elegante",
  "Tireless Spirit": "Espírito Incansável",
  "Rapid Strike": "Golpe Rápido",
  "Strength Before Death": "Força Antes da Morte",
  "Drunken Technique": "Técnica Embriagada",
  "Tipsy Sway": "Balanço Ébrio",
  "Drunkard's Luck": "Sorte do Bêbado",
  "Intoxicated Frenzy": "Frenesi Intoxicado",
  "Path of the Kensei": "Caminho do Kensei",
  "One with the Blade": "Uno com a Lâmina",
  "Sharpen the Blade": "Afiar a Lâmina",
  "Unerring Accuracy": "Precisão Infalível",
  "Radiant Sun Bolt": "Raio Solar Radiante",
  "Searing Arc Strike": "Golpe de Arco Ardente",
  "Searing Sunburst": "Explosão Solar Ardente",
  "Sun Shield": "Escudo Solar",
  "Oath Spells": "Magias do Juramento",
  "Conquering Presence": "Presença Conquistadora",
  "Aura of Conquest": "Aura de Conquista",
  "Scornful Rebuke": "Repreensão Desdenhosa",
  "Invincible Conqueror": "Conquistador Invencível",
  "Emissary of Peace": "Emissário da Paz",
  "Rebuke the Violent": "Repreender o Violento",
  "Aura of the Guardian": "Aura do Guardião",
  "Protective Spirit": "Espírito Protetor",
  "Emissary of Redemption": "Emissário da Redenção",
  "Gloom Stalker Magic": "Magia do Perseguidor Sombrio",
  "Dread Ambusher": "Emboscador Aterrador",
  "Umbral Sight": "Visão Umbral",
  "Iron Mind": "Mente de Ferro",
  "Stalker's Flurry": "Rajada do Perseguidor",
  "Shadowy Dodge": "Esquiva Sombria",
  "Horizon Walker Magic": "Magia do Andarilho do Horizonte",
  "Detect Portal": "Detectar Portal",
  "Planar Warrior": "Guerreiro Planar",
  "Ethereal Step": "Passo Etéreo",
  "Distant Strike": "Golpe Distante",
  "Spectral Defense": "Defesa Espectral",
  "Monster Slayer Magic": "Magia do Matador de Monstros",
  "Hunter's Sense": "Sentido do Caçador",
  "Slayer's Prey": "Presa do Matador",
  "Supernatural Defense": "Defesa Sobrenatural",
  "Magic-User's Nemesis": "Nêmesis de Conjuradores",
  "Slayer's Counter": "Contra-ataque do Matador",
  "Ear for Deceit": "Ouvido para Enganação",
  "Eye for Detail": "Olho para Detalhes",
  "Insightful Fighting": "Combate Perspicaz",
  "Steady Eye": "Olhar Firme",
  "Unerring Eye": "Olhar Infalível",
  "Eye for Weakness": "Olho para Fraquezas",
  "Master of Intrigue": "Mestre da Intriga",
  "Master of Tactics": "Mestre das Táticas",
  "Insightful Manipulator": "Manipulador Perspicaz",
  "Misdirection": "Desorientação",
  "Soul of Deceit": "Alma Enganadora",
  "Skirmisher": "Escaramuçador",
  "Survivalist": "Sobrevivencialista",
  "Superior Mobility": "Mobilidade Superior",
  "Ambush Master": "Mestre da Emboscada",
  "Sudden Strike": "Golpe Súbito",
  "Fancy Footwork": "Passos Elegantes",
  "Rakish Audacity": "Audácia Arrojada",
  "Panache": "Bravata",
  "Elegant Maneuver": "Manobra Elegante",
  "Master Duelist": "Mestre Duelista",
  "Eyes of the Dark": "Olhos da Escuridão",
  "Strength of the Grave": "Força da Sepultura",
  "Hound of Ill Omen": "Cão do Mau Agouro",
  "Shadow Walk": "Caminhada Sombria",
  "Umbral Form": "Forma Umbral",
  "Wind Speaker": "Falante dos Ventos",
  "Tempestuous Magic": "Magia Tempestuosa",
  "Heart of the Storm": "Coração da Tempestade",
  "Storm Guide": "Guia da Tempestade",
  "Storm's Fury": "Fúria da Tempestade",
  "Wind Soul": "Alma do Vento",
  "Arcane Deflection": "Deflexão Arcana",
  "Tactical Wit": "Sagacidade Tática",
  "Power Surge": "Surto de Poder",
  "Durable Magic": "Magia Durável",
  "Deflecting Shroud": "Manto Defletor",
}

const SUBCLASS_NAMES: Record<string, string> = {
  "Path of the Ancestral Guardian": "Caminho do Guardião Ancestral",
  "Path of the Storm Herald": "Caminho do Arauto da Tempestade",
  "Path of the Zealot": "Caminho do Zelote",
  "College of Glamour": "Colégio do Glamour",
  "College of Swords": "Colégio das Espadas",
  "College of Whispers": "Colégio dos Sussurros",
  "Circle of Dreams": "Círculo dos Sonhos",
  "Circle of the Shepherd": "Círculo do Pastor",
  "Arcane Archer": "Arqueiro Arcano",
  Cavalier: "Cavaleiro",
  Samurai: "Samurai",
  "Psi Warrior": "Guerreiro Psiônico",
  "Rune Knight": "Cavaleiro Rúnico",
  "Way of the Open Hand": "Caminho da Mão Aberta",
  "Way of Shadow": "Caminho das Sombras",
  "Way of the Four Elements": "Caminho dos Quatro Elementos",
  "Way of the Astral Self": "Caminho do Eu Astral",
  "Way of Mercy": "Caminho da Misericórdia",
  "Way of the Drunken Master": "Caminho do Mestre Embriagado",
  "Way of the Kensei": "Caminho do Kensei",
  "Way of the Sun Soul": "Caminho da Alma Solar",
  Hunter: "Caçador",
  "Beast Master": "Mestre das Feras",
  "Fey Wanderer": "Andarilho Feérico",
  Swarmkeeper: "Guardião de Enxame",
  "Gloom Stalker": "Perseguidor Sombrio",
  "Horizon Walker": "Andarilho do Horizonte",
  "Monster Slayer": "Matador de Monstros",
  Thief: "Ladrão",
  Assassin: "Assassino",
  Phantom: "Fantasma",
  Soulknife: "Lâmina da Alma",
  Inquisitive: "Inquisitivo",
  Mastermind: "Mestre da Mente",
  Scout: "Batedor",
  Swashbuckler: "Espadachim",
  "Draconic Bloodline": "Linhagem Dracônica",
  "Shadow Magic": "Magia Sombria",
  "Storm Sorcery": "Feitiçaria da Tempestade",
  "War Magic": "Magia de Guerra",
}

const CHOICE_LABELS: Record<string, string> = {
  "Storm environment": "Ambiente da tempestade",
  "College of Swords fighting style": "Estilo de luta do Colégio das Espadas",
  Runes: "Runas",
  "Additional rune": "Runa adicional",
  "Elemental discipline": "Disciplina elemental",
  "Hunter's Prey": "Presa do Caçador",
  "Defensive Tactics": "Táticas defensivas",
  Multiattack: "Ataque múltiplo",
  "Superior Hunter's Defense": "Defesa superior do caçador",
  "Dragon ancestry": "Ancestral dracônico",
}

const OPTION_NAMES: Record<string, string> = {
  "Agonizing Blast": "Rajada Agonizante",
  "Armor of Shadows": "Armadura das Sombras",
  "Ascendant Step": "Passo Ascendente",
  "Beast Speech": "Fala Bestial",
  "Beguiling Influence": "Influência Sedutora",
  "Bewitching Whispers": "Sussurros Enfeitiçantes",
  "Book of Ancient Secrets": "Livro de Segredos Antigos",
  "Chains of Carceri": "Correntes de Cárceri",
  "Devil's Sight": "Visão Diabólica",
  "Dreadful Word": "Palavra Aterradora",
  "Eldritch Mind": "Mente Mística",
  "Eldritch Sight": "Visão Mística",
  "Eldritch Spear": "Lança Mística",
  "Eyes of the Rune Keeper": "Olhos do Guardião das Runas",
  "Fiendish Vigor": "Vigor Infernal",
  "Gaze of Two Minds": "Olhar de Duas Mentes",
  Lifedrinker: "Devorador de Vida",
  "Mask of Many Faces": "Máscara de Muitas Faces",
  "Master of Myriad Forms": "Mestre de Miríades de Formas",
  "Minions of Chaos": "Servos do Caos",
  "Mire the Mind": "Atolar a Mente",
  "Misty Visions": "Visões Enevoadas",
  "One with Shadows": "Uno com as Sombras",
  "Otherworldly Leap": "Salto Transcendental",
  "Repelling Blast": "Rajada Repulsiva",
  "Sculptor of Flesh": "Escultor da Carne",
  "Sign of Ill Omen": "Sinal de Mau Agouro",
  "Thief of Five Fates": "Ladrão dos Cinco Destinos",
  "Thirsting Blade": "Lâmina Sedenta",
  "Visions of Distant Realms": "Visões de Reinos Distantes",
  "Voice of the Chain Master": "Voz do Mestre da Corrente",
  "Whispers of the Grave": "Sussurros da Sepultura",
  "Witch Sight": "Visão de Bruxa",
  "Bond of the Talisman": "Vínculo do Talismã",
  "Far Scribe": "Escriba Distante",
  "Gift of the Protectors": "Dádiva dos Protetores",
  "Investment of the Chain Master": "Investidura do Mestre da Corrente",
  "Protection of the Talisman": "Proteção do Talismã",
  "Rebuke of the Talisman": "Repreensão do Talismã",
  "Undying Servitude": "Servidão Imortal",
  "Commander's Strike": "Ataque do Comandante",
  "Disarming Attack": "Ataque Desarmante",
  "Distracting Strike": "Ataque Distrativo",
  "Evasive Footwork": "Passo Evasivo",
  "Feinting Attack": "Ataque de Finta",
  "Goading Attack": "Ataque Provocador",
  "Lunging Attack": "Ataque de Investida",
  "Maneuvering Attack": "Ataque de Manobra",
  "Menacing Attack": "Ataque Ameaçador",
  Parry: "Aparar",
  "Precision Attack": "Ataque de Precisão",
  "Pushing Attack": "Ataque de Empurrão",
  Rally: "Reagrupar",
  Riposte: "Ripostar",
  "Sweeping Attack": "Ataque Amplo",
  "Trip Attack": "Ataque de Derrubada",
  Ambush: "Emboscada",
  "Bait and Switch": "Isca e Troca",
  Brace: "Preparar",
  "Commanding Presence": "Presença de Comando",
  "Grappling Strike": "Golpe de Agarrão",
  "Quick Toss": "Arremesso Rápido",
  "Tactical Assessment": "Avaliação Tática",
  "Arcane Propulsion Armor": "Armadura de Propulsão Arcana",
  "Armor of Magical Strength": "Armadura de Força Mágica",
  "Boots of the Winding Path": "Botas do Caminho Sinuoso",
  "Enhanced Arcane Focus": "Foco Arcano Aprimorado",
  "Enhanced Defense": "Defesa Aprimorada",
  "Enhanced Weapon": "Arma Aprimorada",
  "Helm of Awareness": "Elmo da Percepção",
  "Homunculus Servant": "Servo Homúnculo",
  "Mind Sharpener": "Afiador Mental",
  "Radiant Weapon": "Arma Radiante",
  "Repeating Shot": "Disparo Repetitivo",
  "Replicate Magic Item": "Replicar Item Mágico",
  "Repulsion Shield": "Escudo de Repulsão",
  "Resistant Armor": "Armadura Resistente",
  "Returning Weapon": "Arma Retornante",
  "Spell-Refueling Ring": "Anel de Reabastecimento Mágico",
  "Elemental Attunement": "Sintonia Elemental",
  "Fangs of the Fire Snake": "Presas da Serpente de Fogo",
  "Fist of Four Thunders": "Punho dos Quatro Trovões",
  "Fist of Unbroken Air": "Punho do Ar Ininterrupto",
  "Rush of the Gale Spirits": "Investida dos Espíritos do Vendaval",
  "Shape the Flowing River": "Moldar o Rio Corrente",
  "Sweeping Cinder Strike": "Golpe Amplo de Cinzas",
  "Water Whip": "Chicote de Água",
  "Clench of the North Wind": "Aperto do Vento Norte",
  "Gong of the Summit": "Gongo do Cume",
  "Flames of the Phoenix": "Chamas da Fênix",
  "Mist Stance": "Postura da Névoa",
  "Ride the Wind": "Cavalgar o Vento",
  "Breath of Winter": "Sopro do Inverno",
  "Eternal Mountain Defense": "Defesa da Montanha Eterna",
  "River of Hungry Flame": "Rio de Chamas Famintas",
  "Wave of Rolling Earth": "Onda de Terra Rolante",
  "Cloud Rune": "Runa da Nuvem",
  "Fire Rune": "Runa do Fogo",
  "Frost Rune": "Runa da Geada",
  "Stone Rune": "Runa da Pedra",
  "Hill Rune": "Runa da Colina",
  "Storm Rune": "Runa da Tempestade",
  "Banishing Arrow": "Flecha de Banimento",
  "Beguiling Arrow": "Flecha Sedutora",
  "Bursting Arrow": "Flecha Explosiva",
  "Enfeebling Arrow": "Flecha Debilitante",
  "Grasping Arrow": "Flecha Agarradora",
  "Piercing Arrow": "Flecha Perfurante",
  "Seeking Arrow": "Flecha Buscadora",
  "Shadow Arrow": "Flecha Sombria",
  Battleaxe: "Machado de batalha",
  Longsword: "Espada longa",
  Warhammer: "Martelo de guerra",
  Whip: "Chicote",
  Longbow: "Arco longo",
  Shortbow: "Arco curto",
  "Heavy Crossbow": "Besta pesada",
  "Hand Crossbow": "Besta de mão",
  "Light Crossbow": "Besta leve",
  Sea: "Mar",
  Tundra: "Tundra",
  "Colossus Slayer": "Matador de Colossos",
  "Giant Killer": "Matador de Gigantes",
  "Horde Breaker": "Quebrador de Hordas",
  "Escape the Horde": "Escapar da Horda",
  "Multiattack Defense": "Defesa contra Ataques Múltiplos",
  "Steel Will": "Vontade de Aço",
  Volley: "Saraivada",
  "Whirlwind Attack": "Ataque Redemoinho",
  Evasion: "Evasão",
  "Stand Against the Tide": "Resistir à Maré",
  "Uncanny Dodge": "Esquiva Sobrenatural",
  "Black — acid": "Negro — ácido",
  "Blue — lightning": "Azul — elétrico",
  "Brass — fire": "Latão — fogo",
  "Bronze — lightning": "Bronze — elétrico",
  "Copper — acid": "Cobre — ácido",
  "Gold — fire": "Dourado — fogo",
  "Green — poison": "Verde — veneno",
  "Red — fire": "Vermelho — fogo",
  "Silver — cold": "Prateado — frio",
  "White — cold": "Branco — frio",
}

export function applyAdditionalProgressionLocalization(
  progressions: Record<ClassName, ClassProgressionDefinition>,
): void {
  for (const progression of Object.values(progressions)) {
    progression.features = progression.features.map(localizeFeature)
    progression.subclasses = progression.subclasses.map((subclass) => ({
      ...subclass,
      name: SUBCLASS_NAMES[subclass.name] ?? subclass.name,
      features: subclass.features.map(localizeFeature),
    }))
  }
}

function localizeFeature<T extends ClassProgressionDefinition["features"][number]>(
  feature: T,
): T {
  const previousName = feature.name
  const nextName = FEATURE_NAMES[previousName] ?? previousName
  const description = feature.description?.startsWith(
    `${previousName} é uma característica`,
  )
    ? feature.description.replace(previousName, nextName)
    : feature.description

  return {
    ...feature,
    name: nextName,
    description,
    choice: feature.choice
      ? {
          ...feature.choice,
          label: CHOICE_LABELS[feature.choice.label] ?? feature.choice.label,
          options: feature.choice.options?.map(
            (option) => OPTION_NAMES[option] ?? option,
          ),
        }
      : undefined,
  }
}
