import type {
  ClassProgressionDefinition,
  LevelChoiceDefinition,
  LevelFeatureDefinition,
} from "./ClassProgression"
import type { ClassName } from "../sheet/Class"

const CLASS_LABELS: Record<ClassName, string> = {
  artificer: "Artífice",
  barbarian: "Bárbaro",
  bard: "Bardo",
  cleric: "Clérigo",
  druid: "Druida",
  fighter: "Guerreiro",
  monk: "Monge",
  paladin: "Paladino",
  ranger: "Patrulheiro",
  rogue: "Ladino",
  sorcerer: "Feiticeiro",
  warlock: "Bruxo",
  wizard: "Mago",
}

const FEATURE_NAMES: Record<string, string> = {
  "Ability Score Improvement": "Aprimoramento de Atributo ou Talento",
  "Spellcasting": "Conjuração",
  "Pact Magic": "Magia de Pacto",
  "Magical Tinkering": "Engenharia Mágica",
  "Infuse Item": "Infundir Item",
  "The Right Tool for the Job": "A Ferramenta Certa para o Trabalho",
  "Tool Expertise": "Especialização com Ferramentas",
  "Flash of Genius": "Lampejo de Genialidade",
  "Magic Item Adept": "Adepto de Itens Mágicos",
  "Spell-Storing Item": "Item que Armazena Magia",
  "Magic Item Savant": "Sábio dos Itens Mágicos",
  "Magic Item Master": "Mestre dos Itens Mágicos",
  "Soul of Artifice": "Alma do Artífice",
  "Rage": "Fúria",
  "Unarmored Defense": "Defesa sem Armadura",
  "Reckless Attack": "Ataque Imprudente",
  "Danger Sense": "Sentido de Perigo",
  "Extra Attack": "Ataque Extra",
  "Fast Movement": "Movimento Rápido",
  "Feral Instinct": "Instinto Selvagem",
  "Brutal Critical": "Crítico Brutal",
  "Relentless Rage": "Fúria Implacável",
  "Persistent Rage": "Fúria Persistente",
  "Indomitable Might": "Força Indomável",
  "Primal Champion": "Campeão Primal",
  "Bardic Inspiration": "Inspiração de Bardo",
  "Jack of All Trades": "Pau para Toda Obra",
  "Song of Rest": "Canção de Descanso",
  "Expertise": "Especialização",
  "Font of Inspiration": "Fonte de Inspiração",
  "Countercharm": "Contraencanto",
  "Magical Secrets": "Segredos Mágicos",
  "Superior Inspiration": "Inspiração Superior",
  "Divine Domain": "Domínio Divino",
  "Channel Divinity": "Canalizar Divindade",
  "Destroy Undead": "Destruir Mortos-vivos",
  "Divine Intervention": "Intervenção Divina",
  "Improved Divine Intervention": "Intervenção Divina Aprimorada",
  "Druidic": "Druídico",
  "Wild Shape": "Forma Selvagem",
  "Wild Shape Improvement": "Aprimoramento da Forma Selvagem",
  "Timeless Body": "Corpo Atemporal",
  "Beast Spells": "Magias de Fera",
  "Archdruid": "Arquídruida",
  "Fighting Style": "Estilo de Luta",
  "Second Wind": "Retomar o Fôlego",
  "Action Surge": "Surto de Ação",
  "Martial Archetype": "Arquétipo Marcial",
  "Indomitable": "Indomável",
  "Unarmored Movement": "Movimento sem Armadura",
  "Martial Arts": "Artes Marciais",
  "Ki": "Ki",
  "Dedicated Weapon": "Arma Dedicada",
  "Deflect Missiles": "Desviar Projéteis",
  "Slow Fall": "Queda Lenta",
  "Stunning Strike": "Ataque Atordoante",
  "Ki-Empowered Strikes": "Ataques Fortalecidos por Ki",
  "Evasion": "Evasão",
  "Stillness of Mind": "Mente Tranquila",
  "Purity of Body": "Pureza Corporal",
  "Tongue of the Sun and Moon": "Língua do Sol e da Lua",
  "Diamond Soul": "Alma de Diamante",
  "Empty Body": "Corpo Vazio",
  "Perfect Self": "Perfeição de Si",
  "Divine Sense": "Sentido Divino",
  "Lay on Hands": "Imposição das Mãos",
  "Divine Smite": "Golpe Divino",
  "Divine Health": "Saúde Divina",
  "Sacred Oath": "Juramento Sagrado",
  "Aura of Protection": "Aura de Proteção",
  "Aura of Courage": "Aura de Coragem",
  "Improved Divine Smite": "Golpe Divino Aprimorado",
  "Cleansing Touch": "Toque Purificador",
  "Favored Enemy": "Inimigo Favorito",
  "Natural Explorer": "Explorador Natural",
  "Deft Explorer": "Explorador Hábil",
  "Favored Foe": "Adversário Favorito",
  "Primeval Awareness": "Consciência Primitiva",
  "Primal Awareness": "Consciência Primordial",
  "Land's Stride": "Passo da Terra",
  "Hide in Plain Sight": "Ocultar-se à Vista",
  "Vanish": "Desaparecer",
  "Feral Senses": "Sentidos Selvagens",
  "Foe Slayer": "Matador de Inimigos",
  "Sneak Attack": "Ataque Furtivo",
  "Thieves' Cant": "Gíria de Ladrão",
  "Cunning Action": "Ação Ardilosa",
  "Roguish Archetype": "Arquétipo de Ladino",
  "Uncanny Dodge": "Esquiva Sobrenatural",
  "Reliable Talent": "Talento Confiável",
  "Blindsense": "Sentido Cego",
  "Slippery Mind": "Mente Escorregadia",
  "Elusive": "Evasivo",
  "Stroke of Luck": "Golpe de Sorte",
  "Sorcerous Origin": "Origem de Feitiçaria",
  "Font of Magic": "Fonte de Magia",
  "Metamagic": "Metamagia",
  "Sorcerous Restoration": "Restauração de Feitiçaria",
  "Otherworldly Patron": "Patrono Transcendental",
  "Eldritch Invocations": "Invocações Místicas",
  "Pact Boon": "Dádiva do Pacto",
  "Mystic Arcanum": "Arcano Místico",
  "Eldritch Master": "Mestre Místico",
  "Arcane Recovery": "Recuperação Arcana",
  "Arcane Tradition": "Tradição Arcana",
  "Spell Mastery": "Domínio de Magia",
  "Signature Spells": "Magias Características",
  "Frenzy": "Frenesi",
  "Mindless Rage": "Fúria Inconsciente",
  "Intimidating Presence": "Presença Intimidante",
  "Retaliation": "Retaliação",
  "Spirit Seeker": "Buscador Espiritual",
  "Totem Spirit": "Espírito Totêmico",
  "Aspect of the Beast": "Aspecto da Fera",
  "Spirit Walker": "Caminhante Espiritual",
  "Totemic Attunement": "Sintonia Totêmica",
  "Form of the Beast": "Forma da Fera",
  "Bestial Soul": "Alma Bestial",
  "Infectious Fury": "Fúria Infecciosa",
  "Call the Hunt": "Chamado da Caçada",
  "Magic Awareness": "Percepção Mágica",
  "Wild Surge": "Surto Selvagem",
  "Bolstering Magic": "Magia Fortalecedora",
  "Unstable Backlash": "Reação Instável",
  "Controlled Surge": "Surto Controlado",
  "Bonus Proficiencies": "Proficiências Adicionais",
  "Cutting Words": "Palavras de Interrupção",
  "Additional Magical Secrets": "Segredos Mágicos Adicionais",
  "Peerless Skill": "Perícia Inigualável",
  "Combat Inspiration": "Inspiração em Combate",
  "Battle Magic": "Magia de Batalha",
  "Mote of Potential": "Partícula de Potencial",
  "Performance of Creation": "Atuação da Criação",
  "Animating Performance": "Atuação Animadora",
  "Creative Crescendo": "Crescendo Criativo",
  "Silver Tongue": "Língua de Prata",
  "Unsettling Words": "Palavras Perturbadoras",
  "Unfailing Inspiration": "Inspiração Infalível",
  "Universal Speech": "Fala Universal",
  "Infectious Inspiration": "Inspiração Contagiante",
  "Disciple of Life": "Discípulo da Vida",
  "Preserve Life": "Preservar a Vida",
  "Blessed Healer": "Curandeiro Abençoado",
  "Divine Strike": "Golpe Divino",
  "Potent Spellcasting": "Conjuração Potente",
  "Supreme Healing": "Cura Suprema",
  "Warding Flare": "Clarão Protetor",
  "Radiance of the Dawn": "Radiância da Alvorada",
  "Improved Flare": "Clarão Aprimorado",
  "Corona of Light": "Coroa de Luz",
  "Acolyte of Nature": "Acólito da Natureza",
  "Dampen Elements": "Amortecer Elementos",
  "Master of Nature": "Mestre da Natureza",
  "Wrath of the Storm": "Ira da Tempestade",
  "Destructive Wrath": "Ira Destrutiva",
  "Thunderbolt Strike": "Golpe Trovejante",
  "Stormborn": "Nascido da Tempestade",
  "Blessing of the Trickster": "Bênção do Trapaceiro",
  "Invoke Duplicity": "Invocar Duplicidade",
  "Cloak of Shadows": "Manto de Sombras",
  "Improved Duplicity": "Duplicidade Aprimorada",
  "War Priest": "Sacerdote da Guerra",
  "Guided Strike": "Golpe Guiado",
  "War God's Blessing": "Bênção do Deus da Guerra",
  "Avatar of Battle": "Avatar da Batalha",
  "Bonus Cantrip": "Truque Adicional",
  "Natural Recovery": "Recuperação Natural",
  "Circle Spells": "Magias do Círculo",
  "Combat Wild Shape": "Forma Selvagem de Combate",
  "Circle Forms": "Formas do Círculo",
  "Primal Strike": "Golpe Primal",
  "Elemental Wild Shape": "Forma Selvagem Elemental",
  "Thousand Forms": "Mil Formas",
  "Halo of Spores": "Halo de Esporos",
  "Symbiotic Entity": "Entidade Simbiótica",
  "Fungal Infestation": "Infestação Fúngica",
  "Spreading Spores": "Esporos Disseminados",
  "Fungal Body": "Corpo Fúngico",
  "Star Map": "Mapa Estelar",
  "Starry Form": "Forma Estrelada",
  "Cosmic Omen": "Presságio Cósmico",
  "Twinkling Constellations": "Constelações Cintilantes",
  "Full of Stars": "Pleno de Estrelas",
  "Summon Wildfire Spirit": "Invocar Espírito de Fogo Selvagem",
  "Enhanced Bond": "Vínculo Aprimorado",
  "Cauterizing Flames": "Chamas Cauterizantes",
  "Blazing Revival": "Renascimento Flamejante",
  "Improved Critical": "Crítico Aprimorado",
  "Remarkable Athlete": "Atleta Extraordinário",
  "Additional Fighting Style": "Estilo de Luta Adicional",
  "Superior Critical": "Crítico Superior",
  "Survivor": "Sobrevivente",
  "Combat Superiority": "Superioridade em Combate",
  "Student of War": "Estudante da Guerra",
  "Know Your Enemy": "Conheça seu Inimigo",
  "Improved Combat Superiority": "Superioridade em Combate Aprimorada",
  "Relentless": "Implacável",
  "Weapon Bond": "Vínculo com Arma",
  "War Magic": "Magia de Guerra",
  "Eldritch Strike": "Golpe Místico",
  "Arcane Charge": "Investida Arcana",
  "Improved War Magic": "Magia de Guerra Aprimorada",
  "Hexblade's Curse": "Maldição da Lâmina Maldita",
  "Hex Warrior": "Guerreiro Hexblade",
  "Accursed Specter": "Espectro Amaldiçoado",
  "Armor of Hexes": "Armadura de Maldições",
  "Master of Hexes": "Mestre das Maldições",
  "Divine Magic": "Magia Divina",
  "Favored by the Gods": "Favorecido pelos Deuses",
  "Empowered Healing": "Cura Fortalecida",
  "Otherworldly Wings": "Asas Transcendentais",
  "Unearthly Recovery": "Recuperação Sobrenatural",
  "Psionic Spells": "Magias Psiônicas",
  "Telepathic Speech": "Fala Telepática",
  "Psionic Sorcery": "Feitiçaria Psiônica",
  "Psychic Defenses": "Defesas Psíquicas",
  "Revelation in Flesh": "Revelação da Carne",
  "Warping Implosion": "Implosão Distorcida",
  "Clockwork Magic": "Magia Mecânica",
  "Restore Balance": "Restaurar Equilíbrio",
  "Bastion of Law": "Bastião da Lei",
  "Trance of Order": "Transe da Ordem",
  "Clockwork Cavalcade": "Cavalgada Mecânica",
}

const SUBCLASS_NAMES: Record<string, string> = {
  "Path of the Berserker": "Caminho do Berserker",
  "Path of the Totem Warrior": "Caminho do Guerreiro Totêmico",
  "Path of the Beast": "Caminho da Fera",
  "Path of Wild Magic": "Caminho da Magia Selvagem",
  "College of Lore": "Colégio do Conhecimento",
  "College of Valor": "Colégio da Bravura",
  "College of Creation": "Colégio da Criação",
  "College of Eloquence": "Colégio da Eloquência",
  "Knowledge Domain": "Domínio do Conhecimento",
  "Life Domain": "Domínio da Vida",
  "Light Domain": "Domínio da Luz",
  "Nature Domain": "Domínio da Natureza",
  "Tempest Domain": "Domínio da Tempestade",
  "Trickery Domain": "Domínio da Trapaça",
  "War Domain": "Domínio da Guerra",
  "Forge Domain": "Domínio da Forja",
  "Grave Domain": "Domínio da Sepultura",
  "Order Domain": "Domínio da Ordem",
  "Peace Domain": "Domínio da Paz",
  "Twilight Domain": "Domínio do Crepúsculo",
  "Circle of the Land": "Círculo da Terra",
  "Circle of the Moon": "Círculo da Lua",
  "Circle of Spores": "Círculo dos Esporos",
  "Circle of Stars": "Círculo das Estrelas",
  "Circle of Wildfire": "Círculo do Fogo Selvagem",
  "Champion": "Campeão",
  "Battle Master": "Mestre de Batalha",
  "Eldritch Knight": "Cavaleiro Arcano",
  "Divine Soul": "Alma Divina",
  "Aberrant Mind": "Mente Aberrante",
  "Clockwork Soul": "Alma Mecânica",
  "The Archfey": "O Arquifada",
  "The Fiend": "O Corruptor",
  "The Great Old One": "O Grande Antigo",
  "The Celestial": "O Celestial",
  "The Hexblade": "A Lâmina Maldita",
  "The Fathomless": "O Insondável",
  "The Genie": "O Gênio",
  "Oath of Devotion": "Juramento de Devoção",
  "Oath of the Ancients": "Juramento dos Anciões",
  "Oath of Vengeance": "Juramento de Vingança",
  "Oath of Conquest": "Juramento de Conquista",
  "Oath of Redemption": "Juramento de Redenção",
  "Oath of Glory": "Juramento de Glória",
  "Oath of the Watchers": "Juramento dos Vigilantes",
  "Arcane Trickster": "Trapaceiro Arcano",
}

const CHOICE_LABELS: Record<string, string> = {
  "Ability Score Improvement or feat": "Aprimoramento de atributo ou talento",
  "Fighting Style": "Estilo de luta",
  "Expertise": "Especialização",
  "Metamagic options": "Opções de Metamagia",
  "Pact boon": "Dádiva do Pacto",
  "Eldritch invocations": "Invocações Místicas",
  "Maneuvers": "Manobras",
  "Additional maneuvers": "Manobras adicionais",
  "Infusions known": "Infusões conhecidas",
  "Elemental disciplines": "Disciplinas elementais",
  "Runes known": "Runas conhecidas",
  "Totem spirit": "Espírito totêmico",
  "Bestial aspect": "Aspecto da fera",
  "Totemic attunement": "Sintonia totêmica",
  "Land type": "Tipo de terreno",
  "Divine affinity": "Afinidade divina",
  "Genie kind": "Tipo de gênio",
  "Arcane Shot options": "Opções de Disparo Arcano",
  "Additional Arcane Shot option": "Disparo Arcano adicional",
  "Initial kensei weapons": "Armas kensei iniciais",
  "Additional kensei weapon": "Arma kensei adicional",
}

const OPTION_NAMES: Record<string, string> = {
  Archery: "Arquearia",
  Defense: "Defesa",
  Dueling: "Duelismo",
  "Great Weapon Fighting": "Combate com Armas Grandes",
  Protection: "Proteção",
  "Two-Weapon Fighting": "Combate com Duas Armas",
  "Blind Fighting": "Combate às Cegas",
  Interception: "Intercepção",
  "Superior Technique": "Técnica Superior",
  "Thrown Weapon Fighting": "Combate com Armas de Arremesso",
  "Unarmed Fighting": "Combate Desarmado",
  "Blessed Warrior": "Guerreiro Abençoado",
  "Druidic Warrior": "Guerreiro Druídico",
  Bear: "Urso",
  Eagle: "Águia",
  Wolf: "Lobo",
  Arctic: "Ártico",
  Coast: "Costa",
  Desert: "Deserto",
  Forest: "Floresta",
  Grassland: "Pradaria",
  Mountain: "Montanha",
  Swamp: "Pântano",
  Underdark: "Umbreterna",
  Good: "Bem",
  Evil: "Mal",
  Law: "Ordem",
  Chaos: "Caos",
  Neutrality: "Neutralidade",
  Dao: "Dao",
  Djinni: "Djinni",
  Efreeti: "Efreeti",
  Marid: "Marid",
  "Pact of the Chain": "Pacto da Corrente",
  "Pact of the Blade": "Pacto da Lâmina",
  "Pact of the Tome": "Pacto do Tomo",
  "Pact of the Talisman": "Pacto do Talismã",
}

const FEATURE_DESCRIPTIONS: Record<string, string> = {
  "Ability Score Improvement": "Aumente atributos dentro dos limites da campanha ou registre um talento obtido neste nível.",
  Spellcasting: "Concede acesso à conjuração da classe. As magias disponíveis e seus limites aparecem na etapa de magias.",
  "Pact Magic": "Concede espaços de magia de pacto, recuperados conforme as regras da classe, e acesso à lista de magias do Bruxo.",
  Expertise: "Escolha perícias ou ferramentas permitidas para dobrar o bônus de proficiência aplicado a elas.",
  Metamagic: "Escolha formas de modificar magias usando pontos de feitiçaria. Cada opção possui custo e condições próprios.",
  "Fighting Style": "Escolha um treinamento marcial permanente entre as opções disponíveis para a classe.",
  "Pact Boon": "Escolha a forma principal da dádiva concedida pelo patrono. A escolha habilita interações e invocações específicas.",
  "Eldritch Invocations": "Escolha melhorias místicas permanentes. Algumas invocações possuem pré-requisitos de nível, pacto ou truque.",
  "Magical Secrets": "Adicione magias de outras listas à lista de magias conhecidas do Bardo, respeitando o nível máximo disponível.",
  "Divine Domain": "Escolha o domínio divino. Ele concede características e magias sempre preparadas nos níveis indicados.",
  "Sacred Oath": "Escolha o juramento do Paladino. Ele concede Canalizar Divindade, auras e magias de juramento.",
  "Otherworldly Patron": "Escolha o patrono do Bruxo. Ele concede características e pode expandir a lista de magias disponíveis.",
  "Sorcerous Origin": "Escolha a origem da magia do Feiticeiro. Ela concede características e, em algumas origens, magias adicionais.",
  "Arcane Tradition": "Escolha a tradição do Mago. Ela especializa o estudo arcano e concede características próprias.",
  "Circle Spells": "Concede magias relacionadas ao círculo druídico. Magias automáticas não consomem o limite normal de preparação.",
}

export function localizeProgressionDefinitions(
  progressions: Record<ClassName, ClassProgressionDefinition>,
): void {
  for (const [className, progression] of Object.entries(progressions) as Array<
    [ClassName, ClassProgressionDefinition]
  >) {
    progression.label = CLASS_LABELS[className]
    progression.features = progression.features.map(localizeFeature)
    progression.subclasses = progression.subclasses.map((subclass) => ({
      ...subclass,
      name: SUBCLASS_NAMES[subclass.name] ?? subclass.name,
      features: subclass.features.map(localizeFeature),
    }))
  }
}

export function localizeFeature(
  feature: LevelFeatureDefinition,
): LevelFeatureDefinition {
  const originalName = feature.name
  const choice = feature.choice ? localizeChoice(feature.choice) : undefined
  const description =
    FEATURE_DESCRIPTIONS[originalName] ??
    localizeExistingDescription(feature.description) ??
    buildFeatureDescription(originalName, feature.level, choice)

  return {
    ...feature,
    name: FEATURE_NAMES[originalName] ?? originalName,
    description,
    choice,
  }
}

export function localizeChoice(
  choice: LevelChoiceDefinition,
): LevelChoiceDefinition {
  return {
    ...choice,
    label: CHOICE_LABELS[choice.label] ?? choice.label,
    description:
      localizeExistingDescription(choice.description) ??
      `Selecione ${choice.count} ${choice.count === 1 ? "opção" : "opções"}. A escolha será registrada na ficha e no evento de progressão.`,
    options: choice.options?.map((option) => OPTION_NAMES[option] ?? option),
  }
}

export function localizeProgressionOption(value: string): string {
  return OPTION_NAMES[value] ?? FEATURE_NAMES[value] ?? value
}

function localizeExistingDescription(value: string | undefined): string | undefined {
  const text = value?.trim()
  if (!text) return undefined
  return text
}

function buildFeatureDescription(
  name: string,
  level: number,
  choice: LevelChoiceDefinition | undefined,
): string {
  const localizedName = FEATURE_NAMES[name] ?? name
  const choiceText = choice
    ? ` Esta característica exige a escolha “${choice.label}”.`
    : ""
  return `${localizedName} é uma característica obtida no nível ${level}.${choiceText}`
}
