import type { Ability } from "../abilities/Ability"
import type { CharacterTemplateProps } from "../characters/CharacterTemplate"
import type { Itemmable } from "../items/item"
import type { MagicCircleLevel } from "../magic/spells/spellDefinitions"
import type { LongRestSupplySelection } from "../supplies/partySupply"

export type GameEntityMetadata = {
  /** Monotonic entity-local version used for future granular sync/conflict checks. */
  version?: number
  /** ISO timestamp of the last operation that touched this entity. */
  updatedAt?: string
  /** User/client that produced the last operation that touched this entity. */
  updatedBy?: string
}

export type InventoryLocation =
  | { type: "party" }
  | { type: "character"; characterId: string }

export type TransferItemOperationRequest = {
  itemId: string
  quantity: number
  from: InventoryLocation
  to: InventoryLocation
  /** Stable id generated by the sender for the copied destination stack. */
  destinationItemId?: string
}

export type GameOperation =
  | {
      type: "character.add"
      character: CharacterTemplateProps
      select?: boolean
    }
  | {
      type: "character.replace"
      characterId: string
      character: CharacterTemplateProps
    }
  | {
      type: "character.delete"
      characterId: string
    }
  | {
      type: "character.longRest.complete"
      characterId: string
      selection: LongRestSupplySelection[]
    }
  | {
      type: "character.hp.set"
      characterId: string
      value: number
    }
  | {
      type: "character.hp.temporary.set"
      characterId: string
      value: number
    }
  | {
      type: "character.hp.damage"
      characterId: string
      amount: number
    }
  | {
      type: "character.hp.heal"
      characterId: string
      amount: number
    }
  | {
      type: "character.ability.add"
      characterId: string
      ability: Ability
    }
  | {
      type: "character.ability.save"
      characterId: string
      ability: Ability
    }
  | {
      type: "character.ability.remove"
      characterId: string
      abilityId: string
    }
  | {
      type: "character.ability.use"
      characterId: string
      abilityId: string
    }
  | {
      type: "character.ability.restore"
      characterId: string
      abilityId: string
    }
  | {
      type: "character.ability.reset"
      characterId: string
      abilityId: string
    }
  | {
      type: "character.spellSlot.spend"
      characterId: string
      level: MagicCircleLevel
    }
  | {
      type: "character.spellSlot.restore"
      characterId: string
      level: MagicCircleLevel
    }
  | {
      type: "character.pactSlot.spend"
      characterId: string
    }
  | {
      type: "character.pactSlot.restore"
      characterId: string
    }
  | {
      type: "party.item.add"
      item: Itemmable
    }
  | {
      type: "party.item.update"
      itemId: string
      item: Itemmable
    }
  | {
      type: "party.item.remove"
      itemId: string
    }
  | {
      type: "inventory.item.transfer"
      request: TransferItemOperationRequest
    }

export type GameOperationRecord = {
  id: string
  schemaVersion: 1
  actorId: string
  createdAt: string
  operation: GameOperation
}

export const MAX_GAME_OPERATION_LOG = 200

export function createGameOperationRecord(
  operation: GameOperation,
  actorId: string,
): GameOperationRecord {
  return {
    id: crypto.randomUUID(),
    schemaVersion: 1,
    actorId: actorId.trim() || "local-user",
    createdAt: new Date().toISOString(),
    operation,
  }
}

export function normalizeGameOperationLog(
  value: unknown,
): GameOperationRecord[] {
  if (!Array.isArray(value)) return []

  return value
    .filter(isGameOperationRecord)
    .slice(-MAX_GAME_OPERATION_LOG)
}

function isGameOperationRecord(value: unknown): value is GameOperationRecord {
  if (!isRecord(value)) return false

  return (
    typeof value.id === "string" &&
    value.schemaVersion === 1 &&
    typeof value.actorId === "string" &&
    typeof value.createdAt === "string" &&
    isGameOperation(value.operation)
  )
}

function isGameOperation(value: unknown): value is GameOperation {
  return isRecord(value) && typeof value.type === "string"
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value)
}
